package com.fredplugins.sailing.features

import com.fredplugins.common.utils.ShimUtils
import com.fredplugins.sailing.FredsSailingConfig
import com.fredplugins.sailing.PluginLifecycleComponent
import com.fredplugins.sailing.SailingUtils
import com.fredplugins.sailing.features.BarracudaTrialHelper.LOST_CARGO_IDS
import com.fredplugins.sailing.features.BarracudaTrialHelper.OBJECTIVE_VARBIT_IDS
import com.fredplugins.sailing.features.BarracudaTrialHelper.PILLAR_VARBIT_IDS
import com.google.inject.Inject
import net.runelite.api.Client
import net.runelite.api.GameObject
import net.runelite.api.events.GameObjectDespawned
import net.runelite.api.events.GameObjectSpawned
import net.runelite.api.events.VarbitChanged
import net.runelite.api.events.WorldViewUnloaded
import net.runelite.api.gameval.ObjectID1.{SAILING_BT_JUBBLY_JIVE_COLLECTABLE_1, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_10, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_11, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_12, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_13, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_14, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_15, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_16, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_17, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_18, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_19, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_2, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_20, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_21, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_22, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_23, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_24, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_25, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_26, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_27, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_28, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_29, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_3, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_30, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_31, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_32, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_33, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_34, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_35, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_36, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_37, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_38, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_39, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_4, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_40, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_41, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_42, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_43, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_44, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_45, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_46, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_47, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_48, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_49, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_5, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_50, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_51, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_52, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_53, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_54, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_55, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_56, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_6, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_7, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_8, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_9, SAILING_BT_JUBBLY_JIVE_COLLECTABLE_SUPPLIES}
import net.runelite.client.eventbus.Subscribe
import net.runelite.client.ui.FontManager
import net.runelite.client.ui.overlay.Overlay
import net.runelite.client.ui.overlay.OverlayLayer
import net.runelite.client.ui.overlay.OverlayPosition
import net.runelite.client.ui.overlay.OverlayUtil
//import com.fredplugins.common.extensions.ObjectExtensions.{composition, impostorComposition, isImpostor, morphId, wrapped}
import com.fredplugins.common.extensions.ActorExtensions.*
import com.fredplugins.common.extensions.ActorExtensions.*
import com.fredplugins.common.extensions.GeneralExtensions.*
import com.fredplugins.common.extensions.ObjectExtensions.*
import com.fredplugins.common.extensions.ProjectileExtensions.*
import com.fredplugins.common.extensions.LocationExtensions.*
import com.fredplugins.common.api.WorldRegion

import java.awt.Dimension
import java.awt.Font
import java.awt.Graphics2D
import scala.collection.mutable
import scala.jdk.CollectionConverters.*
import scala.jdk.OptionConverters.*
import scala.jdk.StreamConverters.*
import scala.util.chaining.*
import scala.util.{Random, Try}
import scala.compiletime.uninitialized

object BarracudaTrialHelper {
	private val LOST_CARGO_IDS = Seq(
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_SUPPLIES,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_1,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_2,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_3,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_4,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_5,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_6,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_7,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_8,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_9,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_10,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_11,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_12,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_13,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_14,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_15,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_16,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_17,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_18,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_19,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_20,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_21,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_22,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_23,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_24,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_25,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_26,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_27,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_28,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_29,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_30,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_31,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_32,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_33,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_34,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_35,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_36,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_37,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_38,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_39,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_40,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_41,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_42,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_43,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_44,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_45,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_46,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_47,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_48,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_49,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_50,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_51,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_52,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_53,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_54,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_55,
		SAILING_BT_JUBBLY_JIVE_COLLECTABLE_56
	)

	private val SAILING_BT_JUBBLY_JIVE_PILLAR_0_STATE_PLAYER = 18411
	private val SAILING_BT_JUBBLY_JIVE_PILLAR_1_STATE_PLAYER = 18412
	private val SAILING_BT_JUBBLY_JIVE_PILLAR_2_STATE_PLAYER = 18413
	private val SAILING_BT_JUBBLY_JIVE_PILLAR_3_STATE_PLAYER = 18414
	private val SAILING_BT_JUBBLY_JIVE_PILLAR_4_STATE_PLAYER = 18415
	private val SAILING_BT_JUBBLY_JIVE_PILLAR_5_STATE_PLAYER = 18416
	private val SAILING_BT_JUBBLY_JIVE_PILLAR_6_STATE_PLAYER = 18417
	private val SAILING_BT_JUBBLY_JIVE_PILLAR_7_STATE_PLAYER = 18418
	private val PILLAR_VARBIT_IDS = Seq(
		SAILING_BT_JUBBLY_JIVE_PILLAR_0_STATE_PLAYER,
		SAILING_BT_JUBBLY_JIVE_PILLAR_1_STATE_PLAYER,
		SAILING_BT_JUBBLY_JIVE_PILLAR_2_STATE_PLAYER,
		SAILING_BT_JUBBLY_JIVE_PILLAR_3_STATE_PLAYER,
		SAILING_BT_JUBBLY_JIVE_PILLAR_4_STATE_PLAYER,
		SAILING_BT_JUBBLY_JIVE_PILLAR_5_STATE_PLAYER,
		SAILING_BT_JUBBLY_JIVE_PILLAR_6_STATE_PLAYER,
		SAILING_BT_JUBBLY_JIVE_PILLAR_7_STATE_PLAYER
	)

	private val SAILING_BT_OBJECTIVE0  = 18448
	private val SAILING_BT_OBJECTIVE1  = 18449
	private val SAILING_BT_OBJECTIVE2  = 18450
	private val SAILING_BT_OBJECTIVE3  = 18451
	private val SAILING_BT_OBJECTIVE4  = 18452
	private val SAILING_BT_OBJECTIVE5  = 18453
	private val SAILING_BT_OBJECTIVE6  = 18454
	private val SAILING_BT_OBJECTIVE7  = 18455
	private val SAILING_BT_OBJECTIVE8  = 18456
	private val SAILING_BT_OBJECTIVE9  = 18457
	private val SAILING_BT_OBJECTIVE10 = 18458
	private val SAILING_BT_OBJECTIVE11 = 18459
	private val SAILING_BT_OBJECTIVE12 = 18460
	private val SAILING_BT_OBJECTIVE13 = 18461
	private val SAILING_BT_OBJECTIVE14 = 18462
	private val SAILING_BT_OBJECTIVE15 = 18463
	private val SAILING_BT_OBJECTIVE16 = 18464
	private val SAILING_BT_OBJECTIVE17 = 18465
	private val SAILING_BT_OBJECTIVE18 = 18466
	private val SAILING_BT_OBJECTIVE19 = 18467
	private val SAILING_BT_OBJECTIVE20 = 18468
	private val SAILING_BT_OBJECTIVE21 = 18469
	private val SAILING_BT_OBJECTIVE22 = 18470
	private val SAILING_BT_OBJECTIVE23 = 18471
	private val SAILING_BT_OBJECTIVE24 = 18472
	private val SAILING_BT_OBJECTIVE25 = 18473
	private val SAILING_BT_OBJECTIVE26 = 18474
	private val SAILING_BT_OBJECTIVE27 = 18475
	private val SAILING_BT_OBJECTIVE28 = 18476
	private val SAILING_BT_OBJECTIVE29 = 18477
	private val SAILING_BT_OBJECTIVE30 = 18478
	private val SAILING_BT_OBJECTIVE31 = 18479
	private val SAILING_BT_OBJECTIVE32 = 18480
	private val SAILING_BT_OBJECTIVE33 = 18481
	private val SAILING_BT_OBJECTIVE34 = 18482
	private val SAILING_BT_OBJECTIVE35 = 18483
	private val SAILING_BT_OBJECTIVE36 = 18484
	private val SAILING_BT_OBJECTIVE37 = 18485
	private val SAILING_BT_OBJECTIVE38 = 18486
	private val SAILING_BT_OBJECTIVE39 = 18487
	private val SAILING_BT_OBJECTIVE40 = 18488
	private val SAILING_BT_OBJECTIVE41 = 18489
	private val SAILING_BT_OBJECTIVE42 = 18490
	private val SAILING_BT_OBJECTIVE43 = 18491
	private val SAILING_BT_OBJECTIVE44 = 18492
	private val SAILING_BT_OBJECTIVE45 = 18493
	private val SAILING_BT_OBJECTIVE46 = 18494
	private val SAILING_BT_OBJECTIVE47 = 18495
	private val SAILING_BT_OBJECTIVE48 = 18496
	private val SAILING_BT_OBJECTIVE49 = 18497
	private val SAILING_BT_OBJECTIVE50 = 18498
	private val SAILING_BT_OBJECTIVE51 = 18499
	private val SAILING_BT_OBJECTIVE52 = 18500
	private val SAILING_BT_OBJECTIVE53 = 18501
	private val SAILING_BT_OBJECTIVE54 = 18502
	private val SAILING_BT_OBJECTIVE55 = 18503
	private val SAILING_BT_OBJECTIVE56 = 18504
	private val SAILING_BT_OBJECTIVE57 = 18505
	private val SAILING_BT_OBJECTIVE58 = 18506
	private val SAILING_BT_OBJECTIVE59 = 18507
	private val SAILING_BT_OBJECTIVE60 = 18508
	private val SAILING_BT_OBJECTIVE61 = 18509
	private val SAILING_BT_OBJECTIVE62 = 18510
	private val SAILING_BT_OBJECTIVE63 = 18511
	private val SAILING_BT_OBJECTIVE64 = 18512
	private val SAILING_BT_OBJECTIVE65 = 18513
	private val SAILING_BT_OBJECTIVE66 = 18514
	private val SAILING_BT_OBJECTIVE67 = 18515
	private val SAILING_BT_OBJECTIVE68 = 18516
	private val SAILING_BT_OBJECTIVE69 = 18517
	private val SAILING_BT_OBJECTIVE70 = 18518
	private val SAILING_BT_OBJECTIVE71 = 18519
	private val SAILING_BT_OBJECTIVE72 = 18520
	private val SAILING_BT_OBJECTIVE73 = 18521
	private val SAILING_BT_OBJECTIVE74 = 18522
	private val SAILING_BT_OBJECTIVE75 = 18523
	private val SAILING_BT_OBJECTIVE76 = 18524
	private val SAILING_BT_OBJECTIVE77 = 18525
	private val SAILING_BT_OBJECTIVE78 = 18526
	private val SAILING_BT_OBJECTIVE79 = 18527
	private val SAILING_BT_OBJECTIVE80 = 18528
	private val SAILING_BT_OBJECTIVE81 = 18529
	private val SAILING_BT_OBJECTIVE82 = 18530
	private val SAILING_BT_OBJECTIVE83 = 18531
	private val SAILING_BT_OBJECTIVE84 = 18532
	private val SAILING_BT_OBJECTIVE85 = 18533
	private val SAILING_BT_OBJECTIVE86 = 18534
	private val SAILING_BT_OBJECTIVE87 = 18535
	private val SAILING_BT_OBJECTIVE88 = 18536
	private val SAILING_BT_OBJECTIVE89 = 18537
	private val SAILING_BT_OBJECTIVE90 = 18538
	private val SAILING_BT_OBJECTIVE91 = 18539
	private val SAILING_BT_OBJECTIVE92 = 18540
	private val SAILING_BT_OBJECTIVE93 = 18541
	private val SAILING_BT_OBJECTIVE94 = 18542
	private val SAILING_BT_OBJECTIVE95 = 18543

	private val OBJECTIVE_VARBIT_IDS = Seq(
		SAILING_BT_OBJECTIVE0,
		SAILING_BT_OBJECTIVE1,
		SAILING_BT_OBJECTIVE2,
		SAILING_BT_OBJECTIVE3,
		SAILING_BT_OBJECTIVE4,
		SAILING_BT_OBJECTIVE5,
		SAILING_BT_OBJECTIVE6,
		SAILING_BT_OBJECTIVE7,
		SAILING_BT_OBJECTIVE8,
		SAILING_BT_OBJECTIVE9,
		SAILING_BT_OBJECTIVE10,
		SAILING_BT_OBJECTIVE11,
		SAILING_BT_OBJECTIVE12,
		SAILING_BT_OBJECTIVE13,
		SAILING_BT_OBJECTIVE14,
		SAILING_BT_OBJECTIVE15,
		SAILING_BT_OBJECTIVE16,
		SAILING_BT_OBJECTIVE17,
		SAILING_BT_OBJECTIVE18,
		SAILING_BT_OBJECTIVE19,
		SAILING_BT_OBJECTIVE20,
		SAILING_BT_OBJECTIVE21,
		SAILING_BT_OBJECTIVE22,
		SAILING_BT_OBJECTIVE23,
		SAILING_BT_OBJECTIVE24,
		SAILING_BT_OBJECTIVE25,
		SAILING_BT_OBJECTIVE26,
		SAILING_BT_OBJECTIVE27,
		SAILING_BT_OBJECTIVE28,
		SAILING_BT_OBJECTIVE29,
		SAILING_BT_OBJECTIVE30,
		SAILING_BT_OBJECTIVE31,
		SAILING_BT_OBJECTIVE32,
		SAILING_BT_OBJECTIVE33,
		SAILING_BT_OBJECTIVE34,
		SAILING_BT_OBJECTIVE35,
		SAILING_BT_OBJECTIVE36,
		SAILING_BT_OBJECTIVE37,
		SAILING_BT_OBJECTIVE38,
		SAILING_BT_OBJECTIVE39,
		SAILING_BT_OBJECTIVE40,
		SAILING_BT_OBJECTIVE41,
		SAILING_BT_OBJECTIVE42,
		SAILING_BT_OBJECTIVE43,
		SAILING_BT_OBJECTIVE44,
		SAILING_BT_OBJECTIVE45,
		SAILING_BT_OBJECTIVE46,
		SAILING_BT_OBJECTIVE47,
		SAILING_BT_OBJECTIVE48,
		SAILING_BT_OBJECTIVE49,
		SAILING_BT_OBJECTIVE50,
		SAILING_BT_OBJECTIVE51,
		SAILING_BT_OBJECTIVE52,
		SAILING_BT_OBJECTIVE53,
		SAILING_BT_OBJECTIVE54,
		SAILING_BT_OBJECTIVE55,
		SAILING_BT_OBJECTIVE56,
		SAILING_BT_OBJECTIVE57,
		SAILING_BT_OBJECTIVE58,
		SAILING_BT_OBJECTIVE59,
		SAILING_BT_OBJECTIVE60,
		SAILING_BT_OBJECTIVE61,
		SAILING_BT_OBJECTIVE62,
		SAILING_BT_OBJECTIVE63,
		SAILING_BT_OBJECTIVE64,
		SAILING_BT_OBJECTIVE65,
		SAILING_BT_OBJECTIVE66,
		SAILING_BT_OBJECTIVE67,
		SAILING_BT_OBJECTIVE68,
		SAILING_BT_OBJECTIVE69,
		SAILING_BT_OBJECTIVE70,
		SAILING_BT_OBJECTIVE71,
		SAILING_BT_OBJECTIVE72,
		SAILING_BT_OBJECTIVE73,
		SAILING_BT_OBJECTIVE74,
		SAILING_BT_OBJECTIVE75,
		SAILING_BT_OBJECTIVE76,
		SAILING_BT_OBJECTIVE77,
		SAILING_BT_OBJECTIVE78,
		SAILING_BT_OBJECTIVE79,
		SAILING_BT_OBJECTIVE80,
		SAILING_BT_OBJECTIVE81,
		SAILING_BT_OBJECTIVE82,
		SAILING_BT_OBJECTIVE83,
		SAILING_BT_OBJECTIVE84,
		SAILING_BT_OBJECTIVE85,
		SAILING_BT_OBJECTIVE86,
		SAILING_BT_OBJECTIVE87,
		SAILING_BT_OBJECTIVE88,
		SAILING_BT_OBJECTIVE89,
		SAILING_BT_OBJECTIVE90,
		SAILING_BT_OBJECTIVE91,
		SAILING_BT_OBJECTIVE92,
		SAILING_BT_OBJECTIVE93,
		SAILING_BT_OBJECTIVE94,
		SAILING_BT_OBJECTIVE95
	)
}

class BarracudaTrialHelper @Inject()(
	private val client: Client,
	private val config: FredsSailingConfig,
	private val utils: SailingUtils
) extends Overlay with PluginLifecycleComponent with ShimUtils.Logging("DEBUG") {
	setLayer(OverlayLayer.ABOVE_SCENE)
	setPosition(OverlayPosition.DYNAMIC)

	private val lostCargo: mutable.Set[GameObject] = mutable.HashSet.empty[GameObject]

	override def shutDown(): Unit = {
		lostCargo.clear()
	}

	@Subscribe
	def onWorldViewUnloaded(e: WorldViewUnloaded): Unit = {
		if (e.getWorldView.isTopLevel) lostCargo.clear
	}

	@Subscribe
	def onGameObjectSpawned(e: GameObjectSpawned): Unit = {
		val o = e.getGameObject
		if (LOST_CARGO_IDS.contains(o.getId)) lostCargo.add(o)
	}

	@Subscribe
	def onGameObjectDespawned(e: GameObjectDespawned): Unit = {
		lostCargo.remove(e.getGameObject)
	}

	@Subscribe
	def onVarbitChanged(e: VarbitChanged): Unit = {
		if(OBJECTIVE_VARBIT_IDS.contains(e.getVarbitId)) {
			log.debug("objective {} changed state to {}", OBJECTIVE_VARBIT_IDS.indexOf(e.getVarbitId), e.getValue)
		}
		if (PILLAR_VARBIT_IDS.contains(e.getVarbitId)) {
			log.debug("pillar {} changed state to {}", PILLAR_VARBIT_IDS.indexOf(e.getVarbitId),  e.getValue)
		}
	}

	override def render(graphics: Graphics2D): Dimension = {
		val oldFont = graphics.getFont
		val newFont = new Font(FontManager.getRunescapeFont.getName, if (config.getFontBold()) Font.BOLD else Font.PLAIN, config.getFontSize())
		graphics.setFont(newFont)

		given Client = client
		lostCargo.foreach(o => {
			val varbitId = Option(o.composition).map(_.getVarbitId).getOrElse(-1)
			val varbitIdx = if(varbitId != -1) OBJECTIVE_VARBIT_IDS.indexOf(varbitId) else -1
			val d = utils.getTransformedObject(o)
			if(d != null) {
				val text = "C: " + LOST_CARGO_IDS.indexOf(o.getId).toString + " | V: " + varbitIdx+""
				OverlayUtil.renderTileOverlay(graphics, o, text, config.barracudaHighlightLostCratesColour())
			}
		})
		graphics.setFont(oldFont)

		null.asInstanceOf[Dimension]
	}

	override def isEnabled: Boolean = config.barracudaHighlightLostCrates()
}
