/*
 * Copyright (c) 2017, Adam <Adam@sigterm.info>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package packetUtils;

import net.runelite.api.widgets.Widget;

import java.util.Arrays;

/**
 * Represents a group-child {@link Widget} relationship.
 * <p>
 */
public enum WidgetInfoExtended {
    FAIRY_RING_LEFT_ORB_CLOCKWISE(WidgetIDExtended.FAIRY_RING_GROUP_ID, WidgetIDExtended.FairyRing.LEFT_ORB_CLOCKWISE),
    FAIRY_RING_LEFT_ORB_COUNTER_CLOCKWISE(WidgetIDExtended.FAIRY_RING_GROUP_ID, WidgetIDExtended.FairyRing.LEFT_ORB_COUNTER_CLOCKWISE),
    FAIRY_RING_MIDDLE_ORB_CLOCKWISE(WidgetIDExtended.FAIRY_RING_GROUP_ID, WidgetIDExtended.FairyRing.MIDDLE_ORB_CLOCKWISE),
    FAIRY_RING_MIDDLE_ORB_COUNTER_CLOCKWISE(WidgetIDExtended.FAIRY_RING_GROUP_ID, WidgetIDExtended.FairyRing.MIDDLE_ORB_COUNTER_CLOCKWISE),
    FAIRY_RING_RIGHT_ORB_CLOCKWISE(WidgetIDExtended.FAIRY_RING_GROUP_ID, WidgetIDExtended.FairyRing.RIGHT_ORB_CLOCKWISE),
    FAIRY_RING_RIGHT_ORB_COUNTER_CLOCKWISE(WidgetIDExtended.FAIRY_RING_GROUP_ID, WidgetIDExtended.FairyRing.RIGHT_ORB_COUNTER_CLOCKWISE),

    FAIRY_RING_TELEPORT_BUTTON(WidgetIDExtended.FAIRY_RING_GROUP_ID, WidgetIDExtended.FairyRing.TELEPORT_BUTTON),

    WORLD_SWITCHER_BUTTON(WidgetIDExtended.LOGOUT_PANEL_ID, WidgetIDExtended.LogoutPanel.WORLD_SWITCHER_BUTTON),
    LOGOUT_BUTTON(WidgetIDExtended.LOGOUT_PANEL_ID, WidgetIDExtended.LogoutPanel.LOGOUT_BUTTON),

    INVENTORY(WidgetIDExtended.INVENTORY_GROUP_ID, 0),
    FRIENDS_LIST(WidgetIDExtended.FRIENDS_LIST_GROUP_ID, 0),
    IGNORE_LIST(WidgetIDExtended.IGNORE_LIST_GROUP_ID, 0),
    FRIENDS_CHAT(WidgetIDExtended.FRIENDS_CHAT_GROUP_ID, 0),
    RAIDING_PARTY(WidgetIDExtended.RAIDING_PARTY_GROUP_ID, 0),

    WORLD_MAP_VIEW(WidgetIDExtended.WORLD_MAP_GROUP_ID, WidgetIDExtended.WorldMap.MAPVIEW),
    WORLD_MAP_OVERVIEW_MAP(WidgetIDExtended.WORLD_MAP_GROUP_ID, WidgetIDExtended.WorldMap.OVERVIEW_MAP),
    WORLD_MAP_BOTTOM_BAR(WidgetIDExtended.WORLD_MAP_GROUP_ID, WidgetIDExtended.WorldMap.BOTTOM_BAR),
    WORLD_MAP_SEARCH(WidgetIDExtended.WORLD_MAP_GROUP_ID, WidgetIDExtended.WorldMap.SEARCH),
    WORLD_MAP_SURFACE_SELECTOR(WidgetIDExtended.WORLD_MAP_GROUP_ID, WidgetIDExtended.WorldMap.SURFACE_SELECTOR),
    WORLD_MAP_TOOLTIP(WidgetIDExtended.WORLD_MAP_GROUP_ID, WidgetIDExtended.WorldMap.TOOLTIP),

    CLUE_SCROLL_TEXT(WidgetIDExtended.CLUE_SCROLL_GROUP_ID, WidgetIDExtended.Cluescroll.CLUE_TEXT),
    CLUE_SCROLL_REWARD_ITEM_CONTAINER(WidgetIDExtended.CLUE_SCROLL_REWARD_GROUP_ID, WidgetIDExtended.Cluescroll.CLUE_SCROLL_ITEM_CONTAINER),

    EQUIPMENT(WidgetIDExtended.EQUIPMENT_GROUP_ID, 0),
    EQUIPMENT_INVENTORY_ITEMS_CONTAINER(WidgetIDExtended.EQUIPMENT_INVENTORY_GROUP_ID, WidgetIDExtended.Equipment.INVENTORY_ITEM_CONTAINER),

    EMOTE_WINDOW(WidgetIDExtended.EMOTES_GROUP_ID, WidgetIDExtended.Emotes.EMOTE_WINDOW),
    EMOTE_SCROLL_CONTAINER(WidgetIDExtended.EMOTES_GROUP_ID, WidgetIDExtended.Emotes.EMOTE_SCROLL_CONTAINER),
    EMOTE_CONTAINER(WidgetIDExtended.EMOTES_GROUP_ID, WidgetIDExtended.Emotes.EMOTE_CONTAINER),
    EMOTE_SCROLLBAR(WidgetIDExtended.EMOTES_GROUP_ID, WidgetIDExtended.Emotes.EMOTE_SCROLLBAR),

    MUSIC_WINDOW(WidgetIDExtended.MUSIC_GROUP_ID, WidgetIDExtended.Music.CONTAINER),
    MUSIC_TRACK_LIST(WidgetIDExtended.MUSIC_GROUP_ID, WidgetIDExtended.Music.LIST),
    MUSIC_TRACK_SCROLL_CONTAINER(WidgetIDExtended.MUSIC_GROUP_ID, WidgetIDExtended.Music.SCROLL_CONTAINER),
    MUSIC_TRACK_SCROLLBAR(WidgetIDExtended.MUSIC_GROUP_ID, WidgetIDExtended.Music.SCROLLBAR),

    DIARY_QUEST_WIDGET_TITLE(WidgetIDExtended.DIARY_QUEST_GROUP_ID, WidgetIDExtended.Diary.DIARY_TITLE),
    DIARY_QUEST_WIDGET_TEXT(WidgetIDExtended.DIARY_QUEST_GROUP_ID, WidgetIDExtended.Diary.DIARY_TEXT),

    PEST_CONTROL_BOAT_INFO(WidgetIDExtended.PEST_CONTROL_BOAT_GROUP_ID, 2),
    PEST_CONTROL_KNIGHT_INFO_CONTAINER(WidgetIDExtended.PEST_CONTROL_GROUP_ID, WidgetIDExtended.PestControl.KNIGHT_INFO_CONTAINER),
    PEST_CONTROL_ACTIVITY_SHIELD_INFO_CONTAINER(WidgetIDExtended.PEST_CONTROL_GROUP_ID, WidgetIDExtended.PestControl.ACTIVITY_SHIELD_CONTAINER),
    PEST_CONTROL_PURPLE_SHIELD(WidgetIDExtended.PEST_CONTROL_GROUP_ID, WidgetIDExtended.PestControl.PURPLE_SHIELD),
    PEST_CONTROL_BLUE_SHIELD(WidgetIDExtended.PEST_CONTROL_GROUP_ID, WidgetIDExtended.PestControl.BLUE_SHIELD),
    PEST_CONTROL_YELLOW_SHIELD(WidgetIDExtended.PEST_CONTROL_GROUP_ID, WidgetIDExtended.PestControl.YELLOW_SHIELD),
    PEST_CONTROL_RED_SHIELD(WidgetIDExtended.PEST_CONTROL_GROUP_ID, WidgetIDExtended.PestControl.RED_SHIELD),
    PEST_CONTROL_PURPLE_HEALTH(WidgetIDExtended.PEST_CONTROL_GROUP_ID, WidgetIDExtended.PestControl.PURPLE_HEALTH),
    PEST_CONTROL_BLUE_HEALTH(WidgetIDExtended.PEST_CONTROL_GROUP_ID, WidgetIDExtended.PestControl.BLUE_HEALTH),
    PEST_CONTROL_YELLOW_HEALTH(WidgetIDExtended.PEST_CONTROL_GROUP_ID, WidgetIDExtended.PestControl.YELLOW_HEALTH),
    PEST_CONTROL_RED_HEALTH(WidgetIDExtended.PEST_CONTROL_GROUP_ID, WidgetIDExtended.PestControl.RED_HEALTH),
    PEST_CONTROL_PURPLE_ICON(WidgetIDExtended.PEST_CONTROL_GROUP_ID, WidgetIDExtended.PestControl.PURPLE_ICON),
    PEST_CONTROL_BLUE_ICON(WidgetIDExtended.PEST_CONTROL_GROUP_ID, WidgetIDExtended.PestControl.BLUE_ICON),
    PEST_CONTROL_YELLOW_ICON(WidgetIDExtended.PEST_CONTROL_GROUP_ID, WidgetIDExtended.PestControl.YELLOW_ICON),
    PEST_CONTROL_RED_ICON(WidgetIDExtended.PEST_CONTROL_GROUP_ID, WidgetIDExtended.PestControl.RED_ICON),
    PEST_CONTROL_ACTIVITY_BAR(WidgetIDExtended.PEST_CONTROL_GROUP_ID, WidgetIDExtended.PestControl.ACTIVITY_BAR),
    PEST_CONTROL_ACTIVITY_PROGRESS(WidgetIDExtended.PEST_CONTROL_GROUP_ID, WidgetIDExtended.PestControl.ACTIVITY_PROGRESS),

    VOLCANIC_MINE_TIME_LEFT(WidgetIDExtended.VOLCANIC_MINE_GROUP_ID, WidgetIDExtended.VolcanicMine.TIME_LEFT),
    VOLCANIC_MINE_POINTS(WidgetIDExtended.VOLCANIC_MINE_GROUP_ID, WidgetIDExtended.VolcanicMine.POINTS),
    VOLCANIC_MINE_STABILITY(WidgetIDExtended.VOLCANIC_MINE_GROUP_ID, WidgetIDExtended.VolcanicMine.STABILITY),
    VOLCANIC_MINE_PLAYER_COUNT(WidgetIDExtended.VOLCANIC_MINE_GROUP_ID, WidgetIDExtended.VolcanicMine.PLAYER_COUNT),
    VOLCANIC_MINE_VENTS_INFOBOX_GROUP(WidgetIDExtended.VOLCANIC_MINE_GROUP_ID, WidgetIDExtended.VolcanicMine.VENTS_INFOBOX_CONTAINER),
    VOLCANIC_MINE_STABILITY_INFOBOX_GROUP(WidgetIDExtended.VOLCANIC_MINE_GROUP_ID, WidgetIDExtended.VolcanicMine.STABILITY_INFOBOX_CONTAINER),
    VOLCANIC_MINE_VENT_A_PERCENTAGE(WidgetIDExtended.VOLCANIC_MINE_GROUP_ID, WidgetIDExtended.VolcanicMine.VENT_A_PERCENTAGE),
    VOLCANIC_MINE_VENT_B_PERCENTAGE(WidgetIDExtended.VOLCANIC_MINE_GROUP_ID, WidgetIDExtended.VolcanicMine.VENT_B_PERCENTAGE),
    VOLCANIC_MINE_VENT_C_PERCENTAGE(WidgetIDExtended.VOLCANIC_MINE_GROUP_ID, WidgetIDExtended.VolcanicMine.VENT_C_PERCENTAGE),
    VOLCANIC_MINE_VENT_A_STATUS(WidgetIDExtended.VOLCANIC_MINE_GROUP_ID, WidgetIDExtended.VolcanicMine.VENT_A_STATUS),
    VOLCANIC_MINE_VENT_B_STATUS(WidgetIDExtended.VOLCANIC_MINE_GROUP_ID, WidgetIDExtended.VolcanicMine.VENT_B_STATUS),
    VOLCANIC_MINE_VENT_C_STATUS(WidgetIDExtended.VOLCANIC_MINE_GROUP_ID, WidgetIDExtended.VolcanicMine.VENT_C_STATUS),

    FRIEND_CHAT_TITLE(WidgetIDExtended.FRIENDS_LIST_GROUP_ID, WidgetIDExtended.FriendList.TITLE),
    FRIEND_LIST_FULL_CONTAINER(WidgetIDExtended.FRIENDS_LIST_GROUP_ID, WidgetIDExtended.FriendList.FULL_CONTAINER),
    FRIEND_LIST_SORT_BY_NAME_BUTTON(WidgetIDExtended.FRIENDS_LIST_GROUP_ID, WidgetIDExtended.FriendList.SORT_BY_NAME_BUTTON),
    FRIEND_LIST_SORT_BY_LAST_WORLD_CHANGE_BUTTON(WidgetIDExtended.FRIENDS_LIST_GROUP_ID, WidgetIDExtended.FriendList.SORT_BY_LAST_WORLD_CHANGE_BUTTON),
    FRIEND_LIST_SORT_BY_WORLD_BUTTON(WidgetIDExtended.FRIENDS_LIST_GROUP_ID, WidgetIDExtended.FriendList.SORT_BY_WORLD_BUTTON),
    FRIEND_LIST_LEGACY_SORT_BUTTON(WidgetIDExtended.FRIENDS_LIST_GROUP_ID, WidgetIDExtended.FriendList.LEGACY_SORT_BUTTON),
    FRIEND_LIST_NAMES_CONTAINER(WidgetIDExtended.FRIENDS_LIST_GROUP_ID, WidgetIDExtended.FriendList.NAMES_CONTAINER),
    FRIEND_LIST_SCROLL_BAR(WidgetIDExtended.FRIENDS_LIST_GROUP_ID, WidgetIDExtended.FriendList.SCROLL_BAR),
    FRIEND_LIST_LOADING_TEXT(WidgetIDExtended.FRIENDS_LIST_GROUP_ID, WidgetIDExtended.FriendList.LOADING_TEXT),
    FRIEND_LIST_PREVIOUS_NAME_HOLDER(WidgetIDExtended.FRIENDS_LIST_GROUP_ID, WidgetIDExtended.FriendList.PREVIOUS_NAME_HOLDER),

    IGNORE_TITLE(WidgetIDExtended.IGNORE_LIST_GROUP_ID, WidgetIDExtended.IgnoreList.TITLE),
    IGNORE_FULL_CONTAINER(WidgetIDExtended.IGNORE_LIST_GROUP_ID, WidgetIDExtended.IgnoreList.FULL_CONTAINER),
    IGNORE_SORT_BY_NAME_BUTTON(WidgetIDExtended.IGNORE_LIST_GROUP_ID, WidgetIDExtended.IgnoreList.SORT_BY_NAME_BUTTON),
    IGNORE_LEGACY_SORT_BUTTON(WidgetIDExtended.IGNORE_LIST_GROUP_ID, WidgetIDExtended.IgnoreList.LEGACY_SORT_BUTTON),
    IGNORE_NAMES_CONTAINER(WidgetIDExtended.IGNORE_LIST_GROUP_ID, WidgetIDExtended.IgnoreList.NAMES_CONTAINER),
    IGNORE_SCROLL_BAR(WidgetIDExtended.IGNORE_LIST_GROUP_ID, WidgetIDExtended.IgnoreList.SCROLL_BAR),
    IGNORE_LOADING_TEXT(WidgetIDExtended.IGNORE_LIST_GROUP_ID, WidgetIDExtended.IgnoreList.LOADING_TEXT),
    IGNORE_PREVIOUS_NAME_HOLDER(WidgetIDExtended.IGNORE_LIST_GROUP_ID, WidgetIDExtended.IgnoreList.PREVIOUS_NAME_HOLDER),

    EXPLORERS_RING_ALCH_INVENTORY(WidgetIDExtended.EXPLORERS_RING_ALCH_GROUP_ID, WidgetIDExtended.ExplorersRing.INVENTORY),

    FRIENDS_CHAT_ROOT(WidgetIDExtended.FRIENDS_CHAT_GROUP_ID, WidgetIDExtended.FriendsChat.ROOT),
    FRIENDS_CHAT_TITLE(WidgetIDExtended.FRIENDS_CHAT_GROUP_ID, WidgetIDExtended.FriendsChat.TITLE),
    FRIENDS_CHAT_OWNER(WidgetIDExtended.FRIENDS_CHAT_GROUP_ID, WidgetIDExtended.FriendsChat.OWNER),
    FRIENDS_CHAT_LIST(WidgetIDExtended.FRIENDS_CHAT_GROUP_ID, WidgetIDExtended.FriendsChat.LIST),

    BANK_CONTAINER(WidgetIDExtended.BANK_GROUP_ID, WidgetIDExtended.Bank.BANK_CONTAINER),
    BANK_SEARCH_BUTTON_BACKGROUND(WidgetIDExtended.BANK_GROUP_ID, WidgetIDExtended.Bank.SEARCH_BUTTON_BACKGROUND),
    BANK_ITEM_CONTAINER(WidgetIDExtended.BANK_GROUP_ID, WidgetIDExtended.Bank.ITEM_CONTAINER),
    BANK_INVENTORY_ITEMS_CONTAINER(WidgetIDExtended.BANK_INVENTORY_GROUP_ID, WidgetIDExtended.Bank.INVENTORY_ITEM_CONTAINER),
    BANK_TITLE_BAR(WidgetIDExtended.BANK_GROUP_ID, WidgetIDExtended.Bank.BANK_TITLE_BAR),
    BANK_INCINERATOR(WidgetIDExtended.BANK_GROUP_ID, WidgetIDExtended.Bank.INCINERATOR),
    BANK_INCINERATOR_CONFIRM(WidgetIDExtended.BANK_GROUP_ID, WidgetIDExtended.Bank.INCINERATOR_CONFIRM),
    BANK_CONTENT_CONTAINER(WidgetIDExtended.BANK_GROUP_ID, WidgetIDExtended.Bank.CONTENT_CONTAINER),
    BANK_DEPOSIT_EQUIPMENT(WidgetIDExtended.BANK_GROUP_ID, WidgetIDExtended.Bank.DEPOSIT_EQUIPMENT),
    BANK_DEPOSIT_INVENTORY(WidgetIDExtended.BANK_GROUP_ID, WidgetIDExtended.Bank.DEPOSIT_INVENTORY),
    BANK_TAB_CONTAINER(WidgetIDExtended.BANK_GROUP_ID, WidgetIDExtended.Bank.TAB_CONTAINER),
    BANK_EQUIPMENT_CONTAINER(WidgetIDExtended.BANK_GROUP_ID, WidgetIDExtended.Bank.EQUIPMENT_CONTENT_CONTAINER),
    BANK_EQUIPMENT_BUTTON(WidgetIDExtended.BANK_GROUP_ID, WidgetIDExtended.Bank.EQUIPMENT_BUTTON),
    BANK_ITEM_COUNT_TOP(WidgetIDExtended.BANK_GROUP_ID, WidgetIDExtended.Bank.ITEM_COUNT_TOP),
    BANK_ITEM_COUNT_BAR(WidgetIDExtended.BANK_GROUP_ID, WidgetIDExtended.Bank.ITEM_COUNT_BAR),
    BANK_ITEM_COUNT_BOTTOM(WidgetIDExtended.BANK_GROUP_ID, WidgetIDExtended.Bank.ITEM_COUNT_BOTTOM),
    BANK_GROUP_STORAGE_BUTTON(WidgetIDExtended.BANK_GROUP_ID, WidgetIDExtended.Bank.GROUP_STORAGE_BUTTON),
    BANK_SCROLLBAR(WidgetIDExtended.BANK_GROUP_ID, WidgetIDExtended.Bank.SCROLLBAR),
    BANK_PIN_CONTAINER(WidgetIDExtended.BANK_PIN_GROUP_ID, WidgetIDExtended.BankPin.CONTAINER),
    BANK_SETTINGS_BUTTON(WidgetIDExtended.BANK_GROUP_ID, WidgetIDExtended.Bank.SETTINGS_BUTTON),
    BANK_TUTORIAL_BUTTON(WidgetIDExtended.BANK_GROUP_ID, WidgetIDExtended.Bank.TUTORIAL_BUTTON),

    GROUP_STORAGE_UI(WidgetIDExtended.GROUP_STORAGE_GROUP_ID, WidgetIDExtended.GroupStorage.UI),
    GROUP_STORAGE_ITEM_CONTAINER(WidgetIDExtended.GROUP_STORAGE_GROUP_ID, WidgetIDExtended.GroupStorage.ITEM_CONTAINER),

    GRAND_EXCHANGE_WINDOW_CONTAINER(WidgetIDExtended.GRAND_EXCHANGE_GROUP_ID, WidgetIDExtended.GrandExchange.WINDOW_CONTAINER),
    GRAND_EXCHANGE_OFFER_CONTAINER(WidgetIDExtended.GRAND_EXCHANGE_GROUP_ID, WidgetIDExtended.GrandExchange.OFFER_CONTAINER),
    GRAND_EXCHANGE_OFFER_TEXT(WidgetIDExtended.GRAND_EXCHANGE_GROUP_ID, WidgetIDExtended.GrandExchange.OFFER_DESCRIPTION),

    GRAND_EXCHANGE_INVENTORY_ITEMS_CONTAINER(WidgetIDExtended.GRAND_EXCHANGE_INVENTORY_GROUP_ID, WidgetIDExtended.GrandExchangeInventory.INVENTORY_ITEM_CONTAINER),

    DEPOSIT_BOX_INVENTORY_ITEMS_CONTAINER(WidgetIDExtended.DEPOSIT_BOX_GROUP_ID, WidgetIDExtended.DepositBox.INVENTORY_ITEM_CONTAINER),

    SHOP_INVENTORY_ITEMS_CONTAINER(WidgetIDExtended.SHOP_INVENTORY_GROUP_ID, WidgetIDExtended.Shop.INVENTORY_ITEM_CONTAINER),

    SMITHING_INVENTORY_ITEMS_CONTAINER(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.INVENTORY_ITEM_CONTAINER),

    GUIDE_PRICES_ITEMS_CONTAINER(WidgetIDExtended.GUIDE_PRICES_GROUP_ID, WidgetIDExtended.GuidePrices.ITEM_CONTAINER),
    GUIDE_PRICES_INVENTORY_ITEMS_CONTAINER(WidgetIDExtended.GUIDE_PRICES_INVENTORY_GROUP_ID, WidgetIDExtended.GuidePrices.INVENTORY_ITEM_CONTAINER),

    RUNE_POUCH_ITEM_CONTAINER(WidgetIDExtended.RUNE_POUCH_GROUP_ID, 0),

    MINIMAP_ORBS(WidgetIDExtended.MINIMAP_GROUP_ID, 0),
    MINIMAP_XP_ORB(WidgetIDExtended.MINIMAP_GROUP_ID, WidgetIDExtended.Minimap.XP_ORB),
    MINIMAP_PRAYER_ORB(WidgetIDExtended.MINIMAP_GROUP_ID, WidgetIDExtended.Minimap.PRAYER_ORB),
    MINIMAP_QUICK_PRAYER_ORB(WidgetIDExtended.MINIMAP_GROUP_ID, WidgetIDExtended.Minimap.QUICK_PRAYER_ORB),
    MINIMAP_PRAYER_ORB_TEXT(WidgetIDExtended.MINIMAP_GROUP_ID, WidgetIDExtended.Minimap.PRAYER_ORB_TEXT),
    MINIMAP_RUN_ORB(WidgetIDExtended.MINIMAP_GROUP_ID, WidgetIDExtended.Minimap.RUN_ORB),
    MINIMAP_TOGGLE_RUN_ORB(WidgetIDExtended.MINIMAP_GROUP_ID, WidgetIDExtended.Minimap.TOGGLE_RUN_ORB),
    MINIMAP_RUN_ORB_TEXT(WidgetIDExtended.MINIMAP_GROUP_ID, WidgetIDExtended.Minimap.RUN_ORB_TEXT),
    MINIMAP_HEALTH_ORB(WidgetIDExtended.MINIMAP_GROUP_ID, WidgetIDExtended.Minimap.HEALTH_ORB),
    MINIMAP_SPEC_ORB(WidgetIDExtended.MINIMAP_GROUP_ID, WidgetIDExtended.Minimap.SPEC_ORB),
    MINIMAP_SPEC_CLICKBOX(WidgetIDExtended.MINIMAP_GROUP_ID, WidgetIDExtended.Minimap.SPEC_CLICKBOX),
    MINIMAP_WORLDMAP_ORB(WidgetIDExtended.MINIMAP_GROUP_ID, WidgetIDExtended.Minimap.WORLDMAP_ORB),
    MINIMAP_WIKI_BANNER_PARENT(WidgetIDExtended.MINIMAP_GROUP_ID, WidgetIDExtended.Minimap.WIKI_BANNER_PARENT),
    MINIMAP_WIKI_BANNER(WidgetIDExtended.MINIMAP_GROUP_ID, WidgetIDExtended.Minimap.WIKI_BANNER),
    MINIMAP_WORLDMAP_OPTIONS(WidgetIDExtended.MINIMAP_GROUP_ID, WidgetIDExtended.Minimap.WORLDMAP_OPTIONS),

    LMS_INFO(WidgetIDExtended.LMS_GROUP_ID, WidgetIDExtended.Lms.INFO),
    LMS_KDA(WidgetIDExtended.LMS_INGAME_GROUP_ID, WidgetIDExtended.LmsKDA.INFO),

    LOGIN_CLICK_TO_PLAY_SCREEN(WidgetIDExtended.LOGIN_CLICK_TO_PLAY_GROUP_ID, 0),
    LOGIN_CLICK_TO_PLAY_SCREEN_MESSAGE_OF_THE_DAY(WidgetIDExtended.LOGIN_CLICK_TO_PLAY_GROUP_ID, WidgetIDExtended.LoginClickToPlayScreen.MESSAGE_OF_THE_DAY),

    FIXED_VIEWPORT(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.FIXED_VIEWPORT),
    FIXED_VIEWPORT_ROOT_INTERFACE_CONTAINER(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.ROOT_INTERFACE_CONTAINER),
    FIXED_VIEWPORT_BANK_CONTAINER(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.BANK_CONTAINER),
    FIXED_VIEWPORT_INTERFACE_CONTAINER(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.INTERFACE_CONTAINER),
    FIXED_VIEWPORT_INVENTORY_CONTAINER(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.INVENTORY_CONTAINER),
    FIXED_VIEWPORT_COMBAT_TAB(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.COMBAT_TAB),
    FIXED_VIEWPORT_STATS_TAB(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.STATS_TAB),
    FIXED_VIEWPORT_QUESTS_TAB(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.QUESTS_TAB),
    FIXED_VIEWPORT_INVENTORY_TAB(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.INVENTORY_TAB),
    FIXED_VIEWPORT_EQUIPMENT_TAB(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.EQUIPMENT_TAB),
    FIXED_VIEWPORT_PRAYER_TAB(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.PRAYER_TAB),
    FIXED_VIEWPORT_MAGIC_TAB(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.MAGIC_TAB),
    FIXED_VIEWPORT_FRIENDS_CHAT_TAB(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.FRIENDS_CHAT_TAB),
    FIXED_VIEWPORT_FRIENDS_TAB(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.FRIENDS_TAB),
    FIXED_VIEWPORT_IGNORES_TAB(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.IGNORES_TAB),
    FIXED_VIEWPORT_LOGOUT_TAB(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.LOGOUT_TAB),
    FIXED_VIEWPORT_OPTIONS_TAB(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.OPTIONS_TAB),
    FIXED_VIEWPORT_EMOTES_TAB(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.EMOTES_TAB),
    FIXED_VIEWPORT_MUSIC_TAB(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.MUSIC_TAB),
    FIXED_VIEWPORT_COMBAT_ICON(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.COMBAT_ICON),
    FIXED_VIEWPORT_STATS_ICON(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.STATS_ICON),
    FIXED_VIEWPORT_QUESTS_ICON(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.QUESTS_ICON),
    FIXED_VIEWPORT_INVENTORY_ICON(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.INVENTORY_ICON),
    FIXED_VIEWPORT_EQUIPMENT_ICON(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.EQUIPMENT_ICON),
    FIXED_VIEWPORT_PRAYER_ICON(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.PRAYER_ICON),
    FIXED_VIEWPORT_MAGIC_ICON(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.MAGIC_ICON),
    FIXED_VIEWPORT_FRIENDS_CHAT_ICON(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.FRIENDS_CHAT_ICON),
    FIXED_VIEWPORT_FRIENDS_ICON(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.FRIENDS_ICON),
    FIXED_VIEWPORT_IGNORES_ICON(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.IGNORES_ICON),
    FIXED_VIEWPORT_LOGOUT_ICON(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.LOGOUT_ICON),
    FIXED_VIEWPORT_OPTIONS_ICON(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.OPTIONS_ICON),
    FIXED_VIEWPORT_EMOTES_ICON(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.EMOTES_ICON),
    FIXED_VIEWPORT_MUSIC_ICON(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.MUSIC_ICON),
    FIXED_VIEWPORT_MINIMAP(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.MINIMAP),
    FIXED_VIEWPORT_MINIMAP_DRAW_AREA(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.MINIMAP_DRAW_AREA),

    RESIZABLE_MINIMAP_STONES_WIDGET(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.MINIMAP),
    RESIZABLE_MINIMAP_STONES_DRAW_AREA(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.MINIMAP_DRAW_AREA),
    RESIZABLE_MINIMAP_STONES_ORB_HOLDER(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.MINIMAP_ORB_HOLDER),
    RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX),
    RESIZABLE_VIEWPORT_COMBAT_TAB(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.COMBAT_TAB),
    RESIZABLE_VIEWPORT_STATS_TAB(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.STATS_TAB),
    RESIZABLE_VIEWPORT_QUESTS_TAB(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.QUESTS_TAB),
    RESIZABLE_VIEWPORT_INVENTORY_TAB(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.INVENTORY_TAB),
    RESIZABLE_VIEWPORT_EQUIPMENT_TAB(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.EQUIPMENT_TAB),
    RESIZABLE_VIEWPORT_PRAYER_TAB(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.PRAYER_TAB),
    RESIZABLE_VIEWPORT_MAGIC_TAB(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.MAGIC_TAB),
    RESIZABLE_VIEWPORT_FRIENDS_CHAT_TAB(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.FRIENDS_CHAT_TAB),
    RESIZABLE_VIEWPORT_FRIENDS_TAB(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.FRIENDS_TAB),
    RESIZABLE_VIEWPORT_IGNORES_TAB(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.IGNORES_TAB),
    RESIZABLE_VIEWPORT_LOGOUT_TAB(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.LOGOUT_TAB),
    RESIZABLE_VIEWPORT_OPTIONS_TAB(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.OPTIONS_TAB),
    RESIZABLE_VIEWPORT_EMOTES_TAB(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.EMOTES_TAB),
    RESIZABLE_VIEWPORT_MUSIC_TAB(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.MUSIC_TAB),
    RESIZABLE_VIEWPORT_COMBAT_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.COMBAT_ICON),
    RESIZABLE_VIEWPORT_STATS_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.STATS_ICON),
    RESIZABLE_VIEWPORT_QUESTS_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.QUESTS_ICON),
    RESIZABLE_VIEWPORT_INVENTORY_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.INVENTORY_ICON),
    RESIZABLE_VIEWPORT_EQUIPMENT_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.EQUIPMENT_ICON),
    RESIZABLE_VIEWPORT_PRAYER_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.PRAYER_ICON),
    RESIZABLE_VIEWPORT_MAGIC_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.MAGIC_ICON),
    RESIZABLE_VIEWPORT_FRIENDS_CHAT_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.FRIENDS_CHAT_ICON),
    RESIZABLE_VIEWPORT_FRIENDS_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.FRIENDS_ICON),
    RESIZABLE_VIEWPORT_IGNORES_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.IGNORES_ICON),
    RESIZABLE_VIEWPORT_LOGOUT_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.LOGOUT_ICON),
    RESIZABLE_VIEWPORT_OPTIONS_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.OPTIONS_ICON),
    RESIZABLE_VIEWPORT_EMOTES_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.EMOTES_ICON),
    RESIZABLE_VIEWPORT_MUSIC_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.MUSIC_ICON),
    RESIZABLE_VIEWPORT_INTERFACE_CONTAINER(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.INTERFACE_CONTAINER),
    RESIZABLE_VIEWPORT_INVENTORY_CONTAINER(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.INVENTORY_CONTAINER),
    RESIZABLE_VIEWPORT_CHATBOX_PARENT(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.CHATBOX_PARENT),
    RESIZABLE_VIEWPORT_INVENTORY_PARENT(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.INVENTORY_PARENT),

    RESIZABLE_MINIMAP_WIDGET(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.MINIMAP),
    RESIZABLE_MINIMAP_DRAW_AREA(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.MINIMAP_DRAW_AREA),
    RESIZABLE_MINIMAP_ORB_HOLDER(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.MINIMAP_ORB_HOLDER),
    RESIZABLE_MINIMAP_LOGOUT_BUTTON(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.MINIMAP_LOGOUT_BUTTON),
    RESIZABLE_VIEWPORT_BOTTOM_LINE(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.RESIZABLE_VIEWPORT_BOTTOM_LINE),
    RESIZABLE_VIEWPORT_BOTTOM_LINE_LOGOUT_BUTTON(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.LOGOUT_BUTTON_OVERLAY),
    RESIZABLE_VIEWPORT_BOTTOM_LINE_QUESTS_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.QUESTS_ICON),
    RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_TAB(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.INVENTORY_TAB),
    RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.INVENTORY_ICON),
    RESIZABLE_VIEWPORT_BOTTOM_LINE_PRAYER_TAB(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.PRAYER_TAB),
    RESIZABLE_VIEWPORT_BOTTOM_LINE_PRAYER_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.PRAYER_ICON),
    RESIZABLE_VIEWPORT_BOTTOM_LINE_EQUIPMENT_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.EQUIP_ICON),
    RESIZABLE_VIEWPORT_BOTTOM_LINE_COMBAT_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.CMB_ICON),
    RESIZABLE_VIEWPORT_BOTTOM_LINE_STATS_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.SKILLS_ICON),
    RESIZABLE_VIEWPORT_BOTTOM_LINE_MAGIC_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.MAGIC_ICON),
    RESIZABLE_VIEWPORT_BOTTOM_LINE_FRIEND_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.FRIEND_ICON),
    RESIZABLE_VIEWPORT_BOTTOM_LINE_FRIEND_CHAT_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.FC_ICON),
    RESIZABLE_VIEWPORT_BOTTOM_LINE_OPTIONS_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.SETTINGS_ICON),
    RESIZABLE_VIEWPORT_BOTTOM_LINE_EMOTES_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.EMOTE_ICON),
    RESIZABLE_VIEWPORT_BOTTOM_LINE_MUSIC_ICON(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.MUSIC_ICON),
    RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_CONTAINER(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.INVENTORY_CONTAINER),
    RESIZABLE_VIEWPORT_BOTTOM_LINE_INTERFACE_CONTAINER(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.INTERFACE_CONTAINER),
    RESIZABLE_VIEWPORT_BOTTOM_LINE_CHATBOX_PARENT(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.CHATBOX_PARENT),
    RESIZABLE_VIEWPORT_BOTTOM_LINE_TABS1(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.TABS1),
    RESIZABLE_VIEWPORT_BOTTOM_LINE_TABS2(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.TABS2),
    RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_PARENT(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.INVENTORY_PARENT),

    PRAYER_THICK_SKIN(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.THICK_SKIN),
    PRAYER_BURST_OF_STRENGTH(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.BURST_OF_STRENGTH),
    PRAYER_CLARITY_OF_THOUGHT(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.CLARITY_OF_THOUGHT),
    PRAYER_SHARP_EYE(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.SHARP_EYE),
    PRAYER_MYSTIC_WILL(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.MYSTIC_WILL),
    PRAYER_ROCK_SKIN(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.ROCK_SKIN),
    PRAYER_SUPERHUMAN_STRENGTH(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.SUPERHUMAN_STRENGTH),
    PRAYER_IMPROVED_REFLEXES(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.IMPROVED_REFLEXES),
    PRAYER_RAPID_RESTORE(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.RAPID_RESTORE),
    PRAYER_RAPID_HEAL(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.RAPID_HEAL),
    PRAYER_PROTECT_ITEM(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.PROTECT_ITEM),
    PRAYER_HAWK_EYE(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.HAWK_EYE),
    PRAYER_MYSTIC_LORE(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.MYSTIC_LORE),
    PRAYER_STEEL_SKIN(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.STEEL_SKIN),
    PRAYER_ULTIMATE_STRENGTH(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.ULTIMATE_STRENGTH),
    PRAYER_INCREDIBLE_REFLEXES(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.INCREDIBLE_REFLEXES),
    PRAYER_PROTECT_FROM_MAGIC(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.PROTECT_FROM_MAGIC),
    PRAYER_PROTECT_FROM_MISSILES(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.PROTECT_FROM_MISSILES),
    PRAYER_PROTECT_FROM_MELEE(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.PROTECT_FROM_MELEE),
    PRAYER_EAGLE_EYE(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.EAGLE_EYE),
    PRAYER_MYSTIC_MIGHT(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.MYSTIC_MIGHT),
    PRAYER_RETRIBUTION(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.RETRIBUTION),
    PRAYER_REDEMPTION(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.REDEMPTION),
    PRAYER_SMITE(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.SMITE),
    PRAYER_PRESERVE(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.PRESERVE),
    PRAYER_CHIVALRY(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.CHIVALRY),
    PRAYER_PIETY(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.PIETY),
    PRAYER_RIGOUR(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.RIGOUR),
    PRAYER_AUGURY(WidgetIDExtended.PRAYER_GROUP_ID, WidgetIDExtended.Prayer.AUGURY),
//    PRAYER_RP_REJUVENATION(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RP_REJUVENATION),
//    PRAYER_RP_ANCIENT_STRENGTH(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RP_ANCIENT_STRENGTH),
//    PRAYER_RP_ANCIENT_SIGHT(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RP_ANCIENT_SIGHT),
//    PRAYER_RP_ANCIENT_WILL(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RP_ANCIENT_WILL),
//    PRAYER_RP_PROTECT_ITEM(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RP_PROTECT_ITEM),
//    PRAYER_RP_RUINOUS_GRACE(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RP_RUINOUS_GRACE),
//    PRAYER_RP_DAMPEN_MAGIC(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RP_DAMPEN_MAGIC),
//    PRAYER_RP_DAMPEN_RANGED(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RP_DAMPEN_RANGED),
//    PRAYER_RP_DAMPEN_MELEE(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RP_DAMPEN_MELEE),
//    PRAYER_RP_TRINITAS(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RP_TRINITAS),
//    PRAYER_RP_BERSERKER(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RP_BERSERKER),
//    PRAYER_RP_PURGE(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RP_PURGE),
//    PRAYER_RP_METABOLISE(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RP_METABOLISE),
//    PRAYER_RP_REBUKE(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RP_REBUKE),
//    PRAYER_RP_VINDICATION(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RP_VINDICATION),
//    PRAYER_RP_DECIMATE(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RP_DECIMATE),
//    PRAYER_RP_ANNIHILATE(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RP_ANNIHILATE),
//    PRAYER_RP_VAPORISE(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RP_VAPORISE),
//    PRAYER_RP_FUMUS_VOW(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RP_FUMUS_VOW),
//    PRAYER_RP_UMBRA_VOW(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RP_UMBRA_VOW),
//    PRAYER_RP_CRUORS_VOW(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RP_CRUORS_VOW),
//    PRAYER_RP_GLACIES_VOW(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RP_GLACIES_VOW),
//    PRAYER_RP_WRATH(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RP_WRATH),
//    PRAYER_RP_INTENSIFY(WidgetID.PRAYER_GROUP_ID, WidgetID.Prayer.RP_INTENSIFY),

    QUICK_PRAYER_PRAYERS(WidgetIDExtended.QUICK_PRAYERS_GROUP_ID, WidgetIDExtended.QuickPrayer.PRAYERS),

    COMBAT_LEVEL(WidgetIDExtended.COMBAT_GROUP_ID, WidgetIDExtended.Combat.LEVEL),
    COMBAT_STYLE_ONE(WidgetIDExtended.COMBAT_GROUP_ID, WidgetIDExtended.Combat.STYLE_ONE),
    COMBAT_STYLE_TWO(WidgetIDExtended.COMBAT_GROUP_ID, WidgetIDExtended.Combat.STYLE_TWO),
    COMBAT_STYLE_THREE(WidgetIDExtended.COMBAT_GROUP_ID, WidgetIDExtended.Combat.STYLE_THREE),
    COMBAT_STYLE_FOUR(WidgetIDExtended.COMBAT_GROUP_ID, WidgetIDExtended.Combat.STYLE_FOUR),
    COMBAT_SPELLS(WidgetIDExtended.COMBAT_GROUP_ID, WidgetIDExtended.Combat.SPELLS),
    COMBAT_DEFENSIVE_SPELL_BOX(WidgetIDExtended.COMBAT_GROUP_ID, WidgetIDExtended.Combat.DEFENSIVE_SPELL_BOX),
    COMBAT_DEFENSIVE_SPELL_ICON(WidgetIDExtended.COMBAT_GROUP_ID, WidgetIDExtended.Combat.DEFENSIVE_SPELL_ICON),
    COMBAT_DEFENSIVE_SPELL_SHIELD(WidgetIDExtended.COMBAT_GROUP_ID, WidgetIDExtended.Combat.DEFENSIVE_SPELL_SHIELD),
    COMBAT_DEFENSIVE_SPELL_TEXT(WidgetIDExtended.COMBAT_GROUP_ID, WidgetIDExtended.Combat.DEFENSIVE_SPELL_TEXT),
    COMBAT_SPELL_BOX(WidgetIDExtended.COMBAT_GROUP_ID, WidgetIDExtended.Combat.SPELL_BOX),
    COMBAT_SPELL_ICON(WidgetIDExtended.COMBAT_GROUP_ID, WidgetIDExtended.Combat.SPELL_ICON),
    COMBAT_SPELL_TEXT(WidgetIDExtended.COMBAT_GROUP_ID, WidgetIDExtended.Combat.SPELL_TEXT),
    COMBAT_AUTO_RETALIATE(WidgetIDExtended.COMBAT_GROUP_ID, WidgetIDExtended.Combat.AUTO_RETALIATE),

    DIALOG_OPTION(WidgetIDExtended.DIALOG_OPTION_GROUP_ID, 0),
    DIALOG_OPTION_OPTIONS(WidgetIDExtended.DIALOG_OPTION_GROUP_ID, WidgetIDExtended.DialogOption.OPTIONS),

    DIALOG_SPRITE(WidgetIDExtended.DIALOG_SPRITE_GROUP_ID, 0),
    DIALOG_SPRITE_SPRITE(WidgetIDExtended.DIALOG_SPRITE_GROUP_ID, WidgetIDExtended.DialogSprite.SPRITE),
    DIALOG_SPRITE_TEXT(WidgetIDExtended.DIALOG_SPRITE_GROUP_ID, WidgetIDExtended.DialogSprite.TEXT),

    DIALOG_NPC_NAME(WidgetIDExtended.DIALOG_NPC_GROUP_ID, WidgetIDExtended.DialogNPC.NAME),
    DIALOG_NPC_TEXT(WidgetIDExtended.DIALOG_NPC_GROUP_ID, WidgetIDExtended.DialogNPC.TEXT),
    DIALOG_NPC_HEAD_MODEL(WidgetIDExtended.DIALOG_NPC_GROUP_ID, WidgetIDExtended.DialogNPC.HEAD_MODEL),

    DIALOG_PLAYER(WidgetIDExtended.DIALOG_PLAYER_GROUP_ID, 0),
    DIALOG_PLAYER_TEXT(WidgetIDExtended.DIALOG_PLAYER_GROUP_ID, WidgetIDExtended.DialogPlayer.TEXT),

    PRIVATE_CHAT_MESSAGE(WidgetIDExtended.PRIVATE_CHAT, 0),

    SLAYER_REWARDS_TOPBAR(WidgetIDExtended.SLAYER_REWARDS_GROUP_ID, WidgetIDExtended.SlayerRewards.TOP_BAR),

    CHATBOX_PARENT(WidgetIDExtended.CHATBOX_GROUP_ID, WidgetIDExtended.Chatbox.PARENT),
    CHATBOX(WidgetIDExtended.CHATBOX_GROUP_ID, WidgetIDExtended.Chatbox.FRAME),
    CHATBOX_MESSAGES(WidgetIDExtended.CHATBOX_GROUP_ID, WidgetIDExtended.Chatbox.MESSAGES),
    CHATBOX_BUTTONS(WidgetIDExtended.CHATBOX_GROUP_ID, WidgetIDExtended.Chatbox.BUTTONS),
    CHATBOX_TITLE(WidgetIDExtended.CHATBOX_GROUP_ID, WidgetIDExtended.Chatbox.TITLE),
    CHATBOX_FULL_INPUT(WidgetIDExtended.CHATBOX_GROUP_ID, WidgetIDExtended.Chatbox.FULL_INPUT),
    CHATBOX_GE_SEARCH_RESULTS(WidgetIDExtended.CHATBOX_GROUP_ID, WidgetIDExtended.Chatbox.GE_SEARCH_RESULTS),
    CHATBOX_CONTAINER(WidgetIDExtended.CHATBOX_GROUP_ID, WidgetIDExtended.Chatbox.CONTAINER),
    CHATBOX_REPORT_TEXT(WidgetIDExtended.CHATBOX_GROUP_ID, WidgetIDExtended.Chatbox.REPORT_TEXT),
    CHATBOX_INPUT(WidgetIDExtended.CHATBOX_GROUP_ID, WidgetIDExtended.Chatbox.INPUT),
    CHATBOX_TRANSPARENT_BACKGROUND(WidgetIDExtended.CHATBOX_GROUP_ID, WidgetIDExtended.Chatbox.TRANSPARENT_BACKGROUND),
    CHATBOX_TRANSPARENT_LINES(WidgetIDExtended.CHATBOX_GROUP_ID, WidgetIDExtended.Chatbox.TRANSPARENT_BACKGROUND_LINES),
    CHATBOX_MESSAGE_LINES(WidgetIDExtended.CHATBOX_GROUP_ID, WidgetIDExtended.Chatbox.MESSAGE_LINES),
    CHATBOX_FIRST_MESSAGE(WidgetIDExtended.CHATBOX_GROUP_ID, WidgetIDExtended.Chatbox.FIRST_MESSAGE),
    CHATBOX_TAB_ALL(WidgetIDExtended.CHATBOX_GROUP_ID, WidgetIDExtended.Chatbox.TAB_ALL),
    CHATBOX_TAB_GAME(WidgetIDExtended.CHATBOX_GROUP_ID, WidgetIDExtended.Chatbox.TAB_GAME),
    CHATBOX_TAB_PUBLIC(WidgetIDExtended.CHATBOX_GROUP_ID, WidgetIDExtended.Chatbox.TAB_PUBLIC),
    CHATBOX_TAB_PRIVATE(WidgetIDExtended.CHATBOX_GROUP_ID, WidgetIDExtended.Chatbox.TAB_PRIVATE),
    CHATBOX_TAB_CHANNEL(WidgetIDExtended.CHATBOX_GROUP_ID, WidgetIDExtended.Chatbox.TAB_CHANNEL),
    CHATBOX_TAB_CLAN(WidgetIDExtended.CHATBOX_GROUP_ID, WidgetIDExtended.Chatbox.TAB_CLAN),
    CHATBOX_TAB_TRADE(WidgetIDExtended.CHATBOX_GROUP_ID, WidgetIDExtended.Chatbox.TAB_TRADE),

    BA_TEAM(WidgetIDExtended.BA_TEAM_GROUP_ID, WidgetIDExtended.BarbarianAssault.TEAM),

    BA_HEAL_ROLE_TEXT(WidgetIDExtended.BA_HEALER_GROUP_ID, WidgetIDExtended.BarbarianAssault.ROLE),
    BA_HEAL_ROLE_SPRITE(WidgetIDExtended.BA_HEALER_GROUP_ID, WidgetIDExtended.BarbarianAssault.ROLE_SPRITE),

    BA_HEAL_TEAMMATES(WidgetIDExtended.BA_HEALER_GROUP_ID, WidgetIDExtended.BarbarianAssault.HLR.TEAMMATES),
    BA_HEAL_TEAMMATE1(WidgetIDExtended.BA_HEALER_GROUP_ID, WidgetIDExtended.BarbarianAssault.HLR.TEAMMATE1),
    BA_HEAL_TEAMMATE2(WidgetIDExtended.BA_HEALER_GROUP_ID, WidgetIDExtended.BarbarianAssault.HLR.TEAMMATE2),
    BA_HEAL_TEAMMATE3(WidgetIDExtended.BA_HEALER_GROUP_ID, WidgetIDExtended.BarbarianAssault.HLR.TEAMMATE3),
    BA_HEAL_TEAMMATE4(WidgetIDExtended.BA_HEALER_GROUP_ID, WidgetIDExtended.BarbarianAssault.HLR.TEAMMATE4),

    BA_COLL_ROLE_TEXT(WidgetIDExtended.BA_COLLECTOR_GROUP_ID, WidgetIDExtended.BarbarianAssault.ROLE),
    BA_COLL_ROLE_SPRITE(WidgetIDExtended.BA_COLLECTOR_GROUP_ID, WidgetIDExtended.BarbarianAssault.ROLE_SPRITE),

    BA_ATK_ROLE_TEXT(WidgetIDExtended.BA_ATTACKER_GROUP_ID, WidgetIDExtended.BarbarianAssault.ATK.ROLE),
    BA_ATK_ROLE_SPRITE(WidgetIDExtended.BA_ATTACKER_GROUP_ID, WidgetIDExtended.BarbarianAssault.ATK.ROLE_SPRITE),

    BA_DEF_ROLE_TEXT(WidgetIDExtended.BA_DEFENDER_GROUP_ID, WidgetIDExtended.BarbarianAssault.ROLE),
    BA_DEF_ROLE_SPRITE(WidgetIDExtended.BA_DEFENDER_GROUP_ID, WidgetIDExtended.BarbarianAssault.ROLE_SPRITE),

    BA_REWARD_TEXT(WidgetIDExtended.BA_REWARD_GROUP_ID, WidgetIDExtended.BarbarianAssault.REWARD_TEXT),

    LEVEL_UP(WidgetIDExtended.LEVEL_UP_GROUP_ID, 0),
    LEVEL_UP_SKILL(WidgetIDExtended.LEVEL_UP_GROUP_ID, WidgetIDExtended.LevelUp.SKILL),
    LEVEL_UP_LEVEL(WidgetIDExtended.LEVEL_UP_GROUP_ID, WidgetIDExtended.LevelUp.LEVEL),

    QUEST_COMPLETED(WidgetIDExtended.QUEST_COMPLETED_GROUP_ID, 0),
    QUEST_COMPLETED_NAME_TEXT(WidgetIDExtended.QUEST_COMPLETED_GROUP_ID, WidgetIDExtended.QuestCompleted.NAME_TEXT),

    MOTHERLODE_MINE(WidgetIDExtended.MOTHERLODE_MINE_GROUP_ID, 0),

    GWD_KC(WidgetIDExtended.GWD_KC_GROUP_ID, 5),

    PUZZLE_BOX(WidgetIDExtended.PUZZLE_BOX_GROUP_ID, WidgetIDExtended.PuzzleBox.VISIBLE_BOX),

    LIGHT_BOX(WidgetIDExtended.LIGHT_BOX_GROUP_ID, WidgetIDExtended.LightBox.LIGHT_BOX),
    LIGHT_BOX_CONTENTS(WidgetIDExtended.LIGHT_BOX_GROUP_ID, WidgetIDExtended.LightBox.LIGHT_BULB_CONTAINER),
    LIGHT_BOX_BUTTON_A(WidgetIDExtended.LIGHT_BOX_GROUP_ID, WidgetIDExtended.LightBox.BUTTON_A),
    LIGHT_BOX_BUTTON_B(WidgetIDExtended.LIGHT_BOX_GROUP_ID, WidgetIDExtended.LightBox.BUTTON_B),
    LIGHT_BOX_BUTTON_C(WidgetIDExtended.LIGHT_BOX_GROUP_ID, WidgetIDExtended.LightBox.BUTTON_C),
    LIGHT_BOX_BUTTON_D(WidgetIDExtended.LIGHT_BOX_GROUP_ID, WidgetIDExtended.LightBox.BUTTON_D),
    LIGHT_BOX_BUTTON_E(WidgetIDExtended.LIGHT_BOX_GROUP_ID, WidgetIDExtended.LightBox.BUTTON_E),
    LIGHT_BOX_BUTTON_F(WidgetIDExtended.LIGHT_BOX_GROUP_ID, WidgetIDExtended.LightBox.BUTTON_F),
    LIGHT_BOX_BUTTON_G(WidgetIDExtended.LIGHT_BOX_GROUP_ID, WidgetIDExtended.LightBox.BUTTON_G),
    LIGHT_BOX_BUTTON_H(WidgetIDExtended.LIGHT_BOX_GROUP_ID, WidgetIDExtended.LightBox.BUTTON_H),

    LIGHT_BOX_WINDOW(WidgetIDExtended.LIGHT_BOX_GROUP_ID, WidgetIDExtended.LightBox.LIGHT_BOX_WINDOW),

    NIGHTMARE_ZONE(WidgetIDExtended.NIGHTMARE_ZONE_GROUP_ID, 0),

    NIGHTMARE_PILLAR_HEALTH(WidgetIDExtended.NIGHTMARE_PILLAR_HEALTH_GROUP_ID, 1),

    RAIDS_POINTS_INFOBOX(WidgetIDExtended.RAIDS_GROUP_ID, WidgetIDExtended.Raids.POINTS_INFOBOX),

    RAIDS_PRIVATE_STORAGE_ITEM_CONTAINER(WidgetIDExtended.CHAMBERS_OF_XERIC_STORAGE_UNIT_PRIVATE_GROUP_ID, WidgetIDExtended.ChambersOfXericStorageUnitPrivate.PRIVATE_CHEST_ITEM_CONTAINER),

    TOB_PARTY_INTERFACE(WidgetIDExtended.TOB_GROUP_ID, WidgetIDExtended.Tob.PARTY_INTERFACE),
    TOB_PARTY_STATS(WidgetIDExtended.TOB_GROUP_ID, WidgetIDExtended.Tob.PARTY_STATS),
    TOB_HEALTH_BAR(WidgetIDExtended.TOB_GROUP_ID, WidgetIDExtended.Tob.HEALTHBAR_CONTAINER),

    BLAST_FURNACE_COFFER(WidgetIDExtended.BLAST_FURNACE_GROUP_ID, 2),

    PYRAMID_PLUNDER_DATA(WidgetIDExtended.PYRAMID_PLUNDER_GROUP_ID, 2),

    EXPERIENCE_TRACKER(WidgetIDExtended.EXPERIENCE_TRACKER_GROUP_ID, 0),
    EXPERIENCE_TRACKER_WIDGET(WidgetIDExtended.EXPERIENCE_TRACKER_GROUP_ID, WidgetIDExtended.ExperienceTracker.WIDGET),
    EXPERIENCE_TRACKER_BOTTOM_BAR(WidgetIDExtended.EXPERIENCE_TRACKER_GROUP_ID, WidgetIDExtended.ExperienceTracker.BOTTOM_BAR),

    FISHING_TRAWLER_CONTRIBUTION(WidgetIDExtended.FISHING_TRAWLER_GROUP_ID, 13),
    FISHING_TRAWLER_TIMER(WidgetIDExtended.FISHING_TRAWLER_GROUP_ID, 14),

    TITHE_FARM(WidgetIDExtended.TITHE_FARM_GROUP_ID, 2),

    BARROWS_BROTHERS(WidgetIDExtended.BARROWS_GROUP_ID, WidgetIDExtended.Barrows.BARROWS_BROTHERS),
    BARROWS_POTENTIAL(WidgetIDExtended.BARROWS_GROUP_ID, WidgetIDExtended.Barrows.BARROWS_POTENTIAL),
    BARROWS_PUZZLE_PARENT(WidgetIDExtended.BARROWS_PUZZLE_GROUP_ID, WidgetIDExtended.Barrows_Puzzle.PARENT),
    BARROWS_PUZZLE_ANSWER1(WidgetIDExtended.BARROWS_PUZZLE_GROUP_ID, WidgetIDExtended.Barrows_Puzzle.ANSWER1),
    BARROWS_PUZZLE_ANSWER1_CONTAINER(WidgetIDExtended.BARROWS_PUZZLE_GROUP_ID, WidgetIDExtended.Barrows_Puzzle.ANSWER1_CONTAINER),
    BARROWS_PUZZLE_ANSWER2(WidgetIDExtended.BARROWS_PUZZLE_GROUP_ID, WidgetIDExtended.Barrows_Puzzle.ANSWER2),
    BARROWS_PUZZLE_ANSWER2_CONTAINER(WidgetIDExtended.BARROWS_PUZZLE_GROUP_ID, WidgetIDExtended.Barrows_Puzzle.ANSWER2_CONTAINER),
    BARROWS_PUZZLE_ANSWER3(WidgetIDExtended.BARROWS_PUZZLE_GROUP_ID, WidgetIDExtended.Barrows_Puzzle.ANSWER3),
    BARROWS_PUZZLE_ANSWER3_CONTAINER(WidgetIDExtended.BARROWS_PUZZLE_GROUP_ID, WidgetIDExtended.Barrows_Puzzle.ANSWER3_CONTAINER),
    BARROWS_FIRST_PUZZLE(WidgetIDExtended.BARROWS_PUZZLE_GROUP_ID, WidgetIDExtended.Barrows_Puzzle.SEQUENCE_1),

    BLAST_MINE(WidgetIDExtended.BLAST_MINE_GROUP_ID, 2),

    FAIRY_RING(WidgetIDExtended.FAIRY_RING_GROUP_ID, 0),

    FAIRY_RING_HEADER(WidgetIDExtended.FAIRY_RING_PANEL_GROUP_ID, WidgetIDExtended.FairyRingPanel.HEADER),
    FAIRY_RING_LIST(WidgetIDExtended.FAIRY_RING_PANEL_GROUP_ID, WidgetIDExtended.FairyRingPanel.LIST),
    FAIRY_RING_FAVORITES(WidgetIDExtended.FAIRY_RING_PANEL_GROUP_ID, WidgetIDExtended.FairyRingPanel.FAVORITES),
    FAIRY_RING_LIST_SEPARATOR(WidgetIDExtended.FAIRY_RING_PANEL_GROUP_ID, WidgetIDExtended.FairyRingPanel.SEPARATOR),
    FAIRY_RING_LIST_SCROLLBAR(WidgetIDExtended.FAIRY_RING_PANEL_GROUP_ID, WidgetIDExtended.FairyRingPanel.SCROLLBAR),

    DESTROY_ITEM(WidgetIDExtended.DESTROY_ITEM_GROUP_ID, 0),
    DESTROY_ITEM_NAME(WidgetIDExtended.DESTROY_ITEM_GROUP_ID, WidgetIDExtended.DestroyItem.DESTROY_ITEM_NAME),
    DESTROY_ITEM_YES(WidgetIDExtended.DESTROY_ITEM_GROUP_ID, WidgetIDExtended.DestroyItem.DESTROY_ITEM_YES),
    DESTROY_ITEM_NO(WidgetIDExtended.DESTROY_ITEM_GROUP_ID, WidgetIDExtended.DestroyItem.DESTROY_ITEM_NO),

    VARROCK_MUSEUM_QUESTION(WidgetIDExtended.VARROCK_MUSEUM_QUIZ_GROUP_ID, WidgetIDExtended.VarrockMuseum.VARROCK_MUSEUM_QUESTION),
    VARROCK_MUSEUM_FIRST_ANSWER(WidgetIDExtended.VARROCK_MUSEUM_QUIZ_GROUP_ID, WidgetIDExtended.VarrockMuseum.VARROCK_MUSEUM_FIRST_ANSWER),
    VARROCK_MUSEUM_SECOND_ANSWER(WidgetIDExtended.VARROCK_MUSEUM_QUIZ_GROUP_ID, WidgetIDExtended.VarrockMuseum.VARROCK_MUSEUM_SECOND_ANSWER),
    VARROCK_MUSEUM_THIRD_ANSWER(WidgetIDExtended.VARROCK_MUSEUM_QUIZ_GROUP_ID, WidgetIDExtended.VarrockMuseum.VARROCK_MUSEUM_THIRD_ANSWER),

    KILL_LOG_TITLE(WidgetIDExtended.KILL_LOGS_GROUP_ID, WidgetIDExtended.KillLog.TITLE),
    KILL_LOG_MONSTER(WidgetIDExtended.KILL_LOGS_GROUP_ID, WidgetIDExtended.KillLog.MONSTER),
    KILL_LOG_KILLS(WidgetIDExtended.KILL_LOGS_GROUP_ID, WidgetIDExtended.KillLog.KILLS),
    KILL_LOG_STREAK(WidgetIDExtended.KILL_LOGS_GROUP_ID, WidgetIDExtended.KillLog.STREAK),

    ADVENTURE_LOG(WidgetIDExtended.ADVENTURE_LOG_ID, WidgetIDExtended.AdventureLog.CONTAINER),

    COLLECTION_LOG(WidgetIDExtended.COLLECTION_LOG_ID, WidgetIDExtended.CollectionLog.CONTAINER),

    COLLECTION_LOG_TABS(WidgetIDExtended.COLLECTION_LOG_ID, WidgetIDExtended.CollectionLog.TABS),
    COLLECTION_LOG_ENTRY(WidgetIDExtended.COLLECTION_LOG_ID, WidgetIDExtended.CollectionLog.ENTRY),
    COLLECTION_LOG_ENTRY_HEADER(WidgetIDExtended.COLLECTION_LOG_ID, WidgetIDExtended.CollectionLog.ENTRY_HEADER),
    COLLECTION_LOG_ENTRY_ITEMS(WidgetIDExtended.COLLECTION_LOG_ID, WidgetIDExtended.CollectionLog.ENTRY_ITEMS),

    GENERIC_SCROLL_TEXT(WidgetIDExtended.GENERIC_SCROLL_GROUP_ID, WidgetIDExtended.GenericScroll.TEXT),

    WORLD_SWITCHER_LIST(WidgetIDExtended.WORLD_SWITCHER_GROUP_ID, WidgetIDExtended.WorldSwitcher.WORLD_LIST),

    FOSSIL_ISLAND_OXYGENBAR(WidgetIDExtended.FOSSIL_ISLAND_OXYGENBAR_ID, 1),

    MINIGAME_TELEPORT_BUTTON(WidgetIDExtended.MINIGAME_TAB_ID, WidgetIDExtended.Minigames.TELEPORT_BUTTON),


    PVP_WILDERNESS_SKULL_CONTAINER(WidgetIDExtended.PVP_GROUP_ID, WidgetIDExtended.Pvp.WILDERNESS_SKULL_CONTAINER),
    PVP_SKULL_CONTAINER(WidgetIDExtended.PVP_GROUP_ID, WidgetIDExtended.Pvp.SKULL_CONTAINER),
    PVP_WORLD_SAFE_ZONE(WidgetIDExtended.PVP_GROUP_ID, WidgetIDExtended.Pvp.SAFE_ZONE),

    PVP_WILDERNESS_LEVEL(WidgetIDExtended.PVP_GROUP_ID, WidgetIDExtended.Pvp.WILDERNESS_LEVEL),
    PVP_KILLDEATH_COUNTER(WidgetIDExtended.PVP_GROUP_ID, WidgetIDExtended.Pvp.KILLDEATH_RATIO),

    KOUREND_FAVOUR_OVERLAY(WidgetIDExtended.KOUREND_FAVOUR_GROUP_ID, WidgetIDExtended.KourendFavour.KOUREND_FAVOUR_OVERLAY),
    ZEAH_MESS_HALL_COOKING_DISPLAY(WidgetIDExtended.ZEAH_MESS_HALL_GROUP_ID, WidgetIDExtended.Zeah.MESS_HALL_COOKING_DISPLAY),

    LOOTING_BAG_CONTAINER(WidgetIDExtended.LOOTING_BAG_GROUP_ID, WidgetIDExtended.LootingBag.LOOTING_BAG_INVENTORY),

    SKOTIZO_CONTAINER(WidgetIDExtended.SKOTIZO_GROUP_ID, WidgetIDExtended.Skotizo.CONTAINER),

    QUESTLIST_BOX(WidgetIDExtended.QUESTLIST_GROUP_ID, WidgetIDExtended.QuestList.BOX),
    QUESTLIST_CONTAINER(WidgetIDExtended.QUESTLIST_GROUP_ID, WidgetIDExtended.QuestList.CONTAINER),

    SEED_VAULT_TITLE_CONTAINER(WidgetIDExtended.SEED_VAULT_GROUP_ID, WidgetIDExtended.SeedVault.TITLE_CONTAINER),
    SEED_VAULT_ITEM_CONTAINER(WidgetIDExtended.SEED_VAULT_GROUP_ID, WidgetIDExtended.SeedVault.ITEM_CONTAINER),
    SEED_VAULT_ITEM_TEXT(WidgetIDExtended.SEED_VAULT_GROUP_ID, WidgetIDExtended.SeedVault.ITEM_TEXT),
    SEED_VAULT_INVENTORY_ITEMS_CONTAINER(WidgetIDExtended.SEED_VAULT_INVENTORY_GROUP_ID, WidgetIDExtended.SeedVault.INVENTORY_ITEM_CONTAINER),

    SETTINGS_SIDE_CAMERA_ZOOM_SLIDER_TRACK(WidgetIDExtended.SETTINGS_SIDE_GROUP_ID, WidgetIDExtended.SettingsSide.CAMERA_ZOOM_SLIDER_TRACK),
    SETTINGS_SIDE_MUSIC_SLIDER(WidgetIDExtended.SETTINGS_SIDE_GROUP_ID, WidgetIDExtended.SettingsSide.MUSIC_SLIDER),
    SETTINGS_SIDE_SOUND_EFFECT_SLIDER(WidgetIDExtended.SETTINGS_SIDE_GROUP_ID, WidgetIDExtended.SettingsSide.SOUND_EFFECT_SLIDER),
    SETTINGS_SIDE_AREA_SOUND_SLIDER(WidgetIDExtended.SETTINGS_SIDE_GROUP_ID, WidgetIDExtended.SettingsSide.AREA_SOUND_SLIDER),

    SETTINGS_INIT(WidgetIDExtended.SETTINGS_GROUP_ID, WidgetIDExtended.Settings.INIT),

    ACHIEVEMENT_DIARY_CONTAINER(WidgetIDExtended.ACHIEVEMENT_DIARY_GROUP_ID, WidgetIDExtended.AchievementDiary.CONTAINER),

    SKILLS_CONTAINER(WidgetIDExtended.SKILLS_GROUP_ID, WidgetIDExtended.Skills.CONTAINER),

    GAUNTLET_TIMER_CONTAINER(WidgetIDExtended.GAUNTLET_TIMER_GROUP_ID, WidgetIDExtended.GauntletTimer.CONTAINER),
    HALLOWED_SEPULCHRE_TIMER_CONTAINER(WidgetIDExtended.HALLOWED_SEPULCHRE_TIMER_GROUP_ID, WidgetIDExtended.HallowedSepulchreTimer.CONTAINER),

    HEALTH_OVERLAY_BAR(WidgetIDExtended.HEALTH_OVERLAY_BAR_GROUP_ID, WidgetIDExtended.Health.HEALTHBAR_CONTAINER),
    HEALTH_OVERLAY_BAR_TEXT(WidgetIDExtended.HEALTH_OVERLAY_BAR_GROUP_ID, WidgetIDExtended.Health.HEALTHBAR_TEXT),

    TRAILBLAZER_AREA_TELEPORT(WidgetIDExtended.TRAILBLAZER_AREAS_GROUP_ID, WidgetIDExtended.TrailblazerAreas.TELEPORT),

    MULTICOMBAT_FIXED(WidgetIDExtended.FIXED_VIEWPORT_GROUP_ID, WidgetIDExtended.FixedViewport.MULTICOMBAT_INDICATOR),
    MULTICOMBAT_RESIZABLE_MODERN(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewport.MULTICOMBAT_INDICATOR),
    MULTICOMBAT_RESIZABLE_CLASSIC(WidgetIDExtended.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, WidgetIDExtended.ResizableViewport.MULTICOMBAT_INDICATOR),

    TEMPOROSS_STATUS_INDICATOR(WidgetIDExtended.TEMPOROSS_GROUP_ID, WidgetIDExtended.TemporossStatus.STATUS_INDICATOR),

    CLAN_LAYER(WidgetIDExtended.CLAN_GROUP_ID, WidgetIDExtended.Clan.LAYER),
    CLAN_HEADER(WidgetIDExtended.CLAN_GROUP_ID, WidgetIDExtended.Clan.HEADER),
    CLAN_MEMBER_LIST(WidgetIDExtended.CLAN_GROUP_ID, WidgetIDExtended.Clan.MEMBERS),

    CLAN_GUEST_LAYER(WidgetIDExtended.CLAN_GUEST_GROUP_ID, WidgetIDExtended.ClanGuest.LAYER),
    CLAN_GUEST_HEADER(WidgetIDExtended.CLAN_GUEST_GROUP_ID, WidgetIDExtended.ClanGuest.HEADER),
    CLAN_GUEST_MEMBER_LIST(WidgetIDExtended.CLAN_GUEST_GROUP_ID, WidgetIDExtended.ClanGuest.MEMBERS),

    POH_TREASURE_CHEST_INVENTORY_CONTAINER(WidgetIDExtended.POH_TREASURE_CHEST_INVENTORY_GROUP_ID, 0),

    TRADE_WINDOW_HEADER(WidgetIDExtended.TRADE_WINDOW_GROUP_ID, WidgetIDExtended.Trade.HEADER),

    TOA_PARTY_LAYER(WidgetIDExtended.TOA_PARTY_GROUP_ID, 2),
    TOA_RAID_LAYER(WidgetIDExtended.TOA_RAID_GROUP_ID, 3),
    EQUIPMENT_HELMET(WidgetIDExtended.EQUIPMENT_GROUP_ID, WidgetIDExtended.Equipment.HELMET),
    EQUIPMENT_CAPE(WidgetIDExtended.EQUIPMENT_GROUP_ID, WidgetIDExtended.Equipment.CAPE),
    EQUIPMENT_AMULET(WidgetIDExtended.EQUIPMENT_GROUP_ID, WidgetIDExtended.Equipment.AMULET),
    EQUIPMENT_WEAPON(WidgetIDExtended.EQUIPMENT_GROUP_ID, WidgetIDExtended.Equipment.WEAPON),
    EQUIPMENT_BODY(WidgetIDExtended.EQUIPMENT_GROUP_ID, WidgetIDExtended.Equipment.BODY),
    EQUIPMENT_SHIELD(WidgetIDExtended.EQUIPMENT_GROUP_ID, WidgetIDExtended.Equipment.SHIELD),
    EQUIPMENT_LEGS(WidgetIDExtended.EQUIPMENT_GROUP_ID, WidgetIDExtended.Equipment.LEGS),
    EQUIPMENT_GLOVES(WidgetIDExtended.EQUIPMENT_GROUP_ID, WidgetIDExtended.Equipment.GLOVES),
    EQUIPMENT_BOOTS(WidgetIDExtended.EQUIPMENT_GROUP_ID, WidgetIDExtended.Equipment.BOOTS),
    EQUIPMENT_RING(WidgetIDExtended.EQUIPMENT_GROUP_ID, WidgetIDExtended.Equipment.RING),
    EQUIPMENT_AMMO(WidgetIDExtended.EQUIPMENT_GROUP_ID, WidgetIDExtended.Equipment.AMMO),

    BANK_PIN_TOP_LEFT_TEXT(WidgetIDExtended.BANK_PIN_GROUP_ID, WidgetIDExtended.BankPin.TOP_LEFT_TEXT),
    BANK_PIN_EXIT_BUTTON(WidgetIDExtended.BANK_PIN_GROUP_ID, WidgetIDExtended.BankPin.EXIT_BUTTON),
    BANK_PIN_FORGOT_BUTTON(WidgetIDExtended.BANK_PIN_GROUP_ID, WidgetIDExtended.BankPin.FORGOT_BUTTON),
    BANK_PIN_FIRST_ENTERED(WidgetIDExtended.BANK_PIN_GROUP_ID, WidgetIDExtended.BankPin.FIRST_ENTERED),
    BANK_PIN_SECOND_ENTERED(WidgetIDExtended.BANK_PIN_GROUP_ID, WidgetIDExtended.BankPin.SECOND_ENTERED),
    BANK_PIN_THIRD_ENTERED(WidgetIDExtended.BANK_PIN_GROUP_ID, WidgetIDExtended.BankPin.THIRD_ENTERED),
    BANK_PIN_FOURTH_ENTERED(WidgetIDExtended.BANK_PIN_GROUP_ID, WidgetIDExtended.BankPin.FOURTH_ENTERED),
    BANK_PIN_INSTRUCTION_TEXT(WidgetIDExtended.BANK_PIN_GROUP_ID, WidgetIDExtended.BankPin.INSTRUCTION_TEXT),
    BANK_PIN_1(WidgetIDExtended.BANK_PIN_GROUP_ID, WidgetIDExtended.BankPin.BUTTON_1),
    BANK_PIN_2(WidgetIDExtended.BANK_PIN_GROUP_ID, WidgetIDExtended.BankPin.BUTTON_2),
    BANK_PIN_3(WidgetIDExtended.BANK_PIN_GROUP_ID, WidgetIDExtended.BankPin.BUTTON_3),
    BANK_PIN_4(WidgetIDExtended.BANK_PIN_GROUP_ID, WidgetIDExtended.BankPin.BUTTON_4),
    BANK_PIN_5(WidgetIDExtended.BANK_PIN_GROUP_ID, WidgetIDExtended.BankPin.BUTTON_5),
    BANK_PIN_6(WidgetIDExtended.BANK_PIN_GROUP_ID, WidgetIDExtended.BankPin.BUTTON_6),
    BANK_PIN_7(WidgetIDExtended.BANK_PIN_GROUP_ID, WidgetIDExtended.BankPin.BUTTON_7),
    BANK_PIN_8(WidgetIDExtended.BANK_PIN_GROUP_ID, WidgetIDExtended.BankPin.BUTTON_8),
    BANK_PIN_9(WidgetIDExtended.BANK_PIN_GROUP_ID, WidgetIDExtended.BankPin.BUTTON_9),
    BANK_PIN_10(WidgetIDExtended.BANK_PIN_GROUP_ID, WidgetIDExtended.BankPin.BUTTON_10),
    RESIZABLE_VIEWPORT_BOTTOM_LINE_MAGIC_TAB(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewportBottomLine.MAGIC_TAB),
    MINIGAME_DIALOG(WidgetIDExtended.DIALOG_MINIGAME_GROUP_ID, 0),
    MINIGAME_DIALOG_TEXT(WidgetIDExtended.DIALOG_MINIGAME_GROUP_ID, WidgetIDExtended.MinigameDialog.TEXT),
    MINIGAME_DIALOG_CONTINUE(WidgetIDExtended.DIALOG_MINIGAME_GROUP_ID, WidgetIDExtended.MinigameDialog.CONTINUE),
    PEST_CONTROL_EXCHANGE_WINDOW(WidgetIDExtended.PEST_CONTROL_EXCHANGE_WINDOW_GROUP_ID, 0),
    PEST_CONTROL_EXCHANGE_WINDOW_POINTS(WidgetIDExtended.PEST_CONTROL_EXCHANGE_WINDOW_GROUP_ID, WidgetIDExtended.PestControlExchangeWindow.POINTS),

    GRAND_EXCHANGE_HISTORY_BUTTON(WidgetIDExtended.GRAND_EXCHANGE_GROUP_ID, WidgetIDExtended.GrandExchange.HISTORY_BUTTON),
    GRAND_EXCHANGE_BACK_BUTTON(WidgetIDExtended.GRAND_EXCHANGE_GROUP_ID, WidgetIDExtended.GrandExchange.BACK_BUTTON),
    GRAND_EXCHANGE_OFFER1(WidgetIDExtended.GRAND_EXCHANGE_GROUP_ID, WidgetIDExtended.GrandExchange.OFFER1),
    GRAND_EXCHANGE_OFFER2(WidgetIDExtended.GRAND_EXCHANGE_GROUP_ID, WidgetIDExtended.GrandExchange.OFFER2),
    GRAND_EXCHANGE_OFFER3(WidgetIDExtended.GRAND_EXCHANGE_GROUP_ID, WidgetIDExtended.GrandExchange.OFFER3),
    GRAND_EXCHANGE_OFFER4(WidgetIDExtended.GRAND_EXCHANGE_GROUP_ID, WidgetIDExtended.GrandExchange.OFFER4),
    GRAND_EXCHANGE_OFFER5(WidgetIDExtended.GRAND_EXCHANGE_GROUP_ID, WidgetIDExtended.GrandExchange.OFFER5),
    GRAND_EXCHANGE_OFFER6(WidgetIDExtended.GRAND_EXCHANGE_GROUP_ID, WidgetIDExtended.GrandExchange.OFFER6),
    GRAND_EXCHANGE_OFFER7(WidgetIDExtended.GRAND_EXCHANGE_GROUP_ID, WidgetIDExtended.GrandExchange.OFFER7),
    GRAND_EXCHANGE_OFFER8(WidgetIDExtended.GRAND_EXCHANGE_GROUP_ID, WidgetIDExtended.GrandExchange.OFFER8),

    GRAND_EXCHANGE_OFFER_CONFIRM_BUTTON(WidgetIDExtended.GRAND_EXCHANGE_GROUP_ID, WidgetIDExtended.GrandExchange.OFFER_CONFIRM_BUTTON),

    SMITHING_ANVIL_DAGGER(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.DAGGER),
    SMITHING_ANVIL_SWORD(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.SWORD),
    SMITHING_ANVIL_SCIMITAR(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.SCIMITAR),
    SMITHING_ANVIL_LONG_SWORD(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.LONG_SWORD),
    SMITHING_ANVIL_TWO_H_SWORD(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.TWO_H_SWORD),
    SMITHING_ANVIL_AXE(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.AXE),
    SMITHING_ANVIL_MACE(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.MACE),
    SMITHING_ANVIL_WARHAMMER(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.WARHAMMER),
    SMITHING_ANVIL_BATTLE_AXE(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.BATTLE_AXE),
    SMITHING_ANVIL_CLAWS(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.CLAWS),
    SMITHING_ANVIL_CHAIN_BODY(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.CHAIN_BODY),
    SMITHING_ANVIL_PLATE_LEGS(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.PLATE_LEGS),
    SMITHING_ANVIL_PLATE_SKIRT(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.PLATE_SKIRT),
    SMITHING_ANVIL_PLATE_BODY(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.PLATE_BODY),
    SMITHING_ANVIL_NAILS(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.NAILS),
    SMITHING_ANVIL_MED_HELM(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.MED_HELM),
    SMITHING_ANVIL_FULL_HELM(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.FULL_HELM),
    SMITHING_ANVIL_SQ_SHIELD(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.SQ_SHIELD),
    SMITHING_ANVIL_KITE_SHIELD(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.KITE_SHIELD),
    SMITHING_ANVIL_DART_TIPS(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.DART_TIPS),
    SMITHING_ANVIL_ARROW_HEADS(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.ARROW_HEADS),
    SMITHING_ANVIL_KNIVES(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.KNIVES),
    SMITHING_ANVIL_JAVELIN_HEADS(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.JAVELIN_HEADS),
    SMITHING_ANVIL_BOLTS(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.BOLTS),
    SMITHING_ANVIL_LIMBS(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.LIMBS),
    SMITHING_ANVIL_EXCLUSIVE1(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.EXCLUSIVE1),
    SMITHING_ANVIL_EXCLUSIVE2(WidgetIDExtended.SMITHING_GROUP_ID, WidgetIDExtended.Smithing.EXCLUSIVE2),

    MINIMAP_WORLD_ORB(WidgetIDExtended.MINIMAP_GROUP_ID, WidgetIDExtended.Minimap.WORLDMAP_ORB),

    COMBAT_WEAPON(WidgetIDExtended.COMBAT_GROUP_ID, WidgetIDExtended.Combat.WEAPON_NAME),

    COMBAT_SPECIAL_ATTACK(WidgetIDExtended.COMBAT_GROUP_ID, WidgetIDExtended.Combat.SPECIAL_ATTACK_BAR),
    COMBAT_SPECIAL_ATTACK_CLICKBOX(WidgetIDExtended.COMBAT_GROUP_ID, WidgetIDExtended.Combat.SPECIAL_ATTACK_CLICKBOX),
    COMBAT_TOOLTIP(WidgetIDExtended.COMBAT_GROUP_ID, WidgetIDExtended.Combat.TOOLTIP),

    MULTI_SKILL_MENU(WidgetIDExtended.MULTISKILL_MENU_GROUP_ID, 0),

    DIALOG2_SPRITE(WidgetIDExtended.DIALOG_SPRITE2_ID, 0),
    DIALOG2_SPRITE_SPRITE1(WidgetIDExtended.DIALOG_SPRITE2_ID, WidgetIDExtended.DialogSprite2.SPRITE1),
    DIALOG2_SPRITE_SPRITE2(WidgetIDExtended.DIALOG_SPRITE2_ID, WidgetIDExtended.DialogSprite2.SPRITE2),
    DIALOG2_SPRITE_TEXT(WidgetIDExtended.DIALOG_SPRITE2_ID, WidgetIDExtended.DialogSprite2.TEXT),
    DIALOG2_SPRITE_CONTINUE(WidgetIDExtended.DIALOG_SPRITE2_ID, WidgetIDExtended.DialogSprite2.CONTINUE),

    DIALOG_OPTION_OPTION1(WidgetIDExtended.DIALOG_OPTION_GROUP_ID, WidgetIDExtended.DialogOption.OPTIONS),

    DIALOG_NOTIFICATION_TEXT(WidgetIDExtended.DIALOG_NOTIFICATION_GROUP_ID, WidgetIDExtended.DialogNotification.TEXT),
    DIALOG_NOTIFICATION_CONTINUE(WidgetIDExtended.DIALOG_NOTIFICATION_GROUP_ID, WidgetIDExtended.DialogNotification.CONTINUE),

    LEVEL_UP_CONTINUE(WidgetIDExtended.LEVEL_UP_GROUP_ID, WidgetIDExtended.LevelUp.CONTINUE),

    THEATRE_OF_BLOOD_PARTY(WidgetIDExtended.THEATRE_OF_BLOOD_PARTY_GROUP_ID, WidgetIDExtended.TheatreOfBloodParty.CONTAINER),

    LIGHT_BOX_BUTTON_CONTAINER(WidgetIDExtended.LIGHT_BOX_GROUP_ID, WidgetIDExtended.LightBox.LIGHT_BOX_BUTTON_CONTAINER),

    THEATRE_OF_BLOOD_HEALTH_ORBS(WidgetIDExtended.THEATRE_OF_BLOOD_GROUP_ID, WidgetIDExtended.TheatreOfBlood.ORB_BOX),
    THEATRE_OF_BLOOD_BOSS_HEALTH(WidgetIDExtended.THEATRE_OF_BLOOD_GROUP_ID, WidgetIDExtended.TheatreOfBlood.BOSS_HEALTH_BAR),
    THEATRE_OF_BLOOD_RAIDING_PARTY(WidgetIDExtended.THEATRE_OF_BLOOD_GROUP_ID, WidgetIDExtended.TheatreOfBlood.RAIDING_PARTY),

    WORLD_SWITCHER_CONTAINER(WidgetIDExtended.WORLD_SWITCHER_GROUP_ID, WidgetIDExtended.WorldSwitcher.CONTAINER),

    WORLD_SWITCHER_LOGOUT_BUTTON(WidgetIDExtended.WORLD_SWITCHER_GROUP_ID, WidgetIDExtended.WorldSwitcher.LOGOUT_BUTTON),

    FOSSIL_MUSHROOM_TELEPORT(WidgetIDExtended.FOSSIL_ISLAND_MUSHROOM_TELE_GROUP_ID, WidgetIDExtended.FossilMushroomTeleport.ROOT),
    FOSSIL_MUSHROOM_HOUSE(WidgetIDExtended.FOSSIL_ISLAND_MUSHROOM_TELE_GROUP_ID, WidgetIDExtended.FossilMushroomTeleport.HOUSE_ON_HILL),
    FOSSIL_MUSHROOM_VALLEY(WidgetIDExtended.FOSSIL_ISLAND_MUSHROOM_TELE_GROUP_ID, WidgetIDExtended.FossilMushroomTeleport.VERDANT_VALLEY),
    FOSSIL_MUSHROOM_SWAMP(WidgetIDExtended.FOSSIL_ISLAND_MUSHROOM_TELE_GROUP_ID, WidgetIDExtended.FossilMushroomTeleport.SWAMP),
    FOSSIL_MUSHROOM_MEADOW(WidgetIDExtended.FOSSIL_ISLAND_MUSHROOM_TELE_GROUP_ID, WidgetIDExtended.FossilMushroomTeleport.MUSHROOM_MEADOW),

    SPELLBOOK(WidgetIDExtended.SPELLBOOK_GROUP_ID, 0),
    SPELLBOOK_FILTERED_BOUNDS(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.FILTERED_SPELLS_BOUNDS),

    /* STANDARD SPELL BOOK WIDGETS*/
    SPELL_LUMBRIDGE_HOME_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.LUMBRIDGE_HOME_TELEPORT),
    SPELL_MINIGAME_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.MINIGAME_TELEPORT),
    SPELL_WIND_STRIKE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.WIND_STRIKE),
    SPELL_CONFUSE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.CONFUSE),
    SPELL_ENCHANT_CROSSBOW_BOLT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.ENCHANT_CROSSBOW_BOLT),
    SPELL_WATER_STRIKE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.WATER_STRIKE),
    SPELL_LVL_1_ENCHANT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.LVL_1_ENCHANT),
    SPELL_EARTH_STRIKE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.EARTH_STRIKE),
    SPELL_WEAKEN(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.WEAKEN),
    SPELL_FIRE_STRIKE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.FIRE_STRIKE),
    SPELL_BONES_TO_BANANAS(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.BONES_TO_BANANAS),
    SPELL_WIND_BOLT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.WIND_BOLT),
    SPELL_CURSE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.CURSE),
    SPELL_BIND(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.BIND),
    SPELL_LOW_LEVEL_ALCHEMY(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.LOW_LEVEL_ALCHEMY),
    SPELL_WATER_BOLT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.WATER_BOLT),
    SPELL_VARROCK_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.VARROCK_TELEPORT),
    SPELL_LVL_2_ENCHANT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.LVL_2_ENCHANT),
    SPELL_EARTH_BOLT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.EARTH_BOLT),
    SPELL_LUMBRIDGE_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.LUMBRIDGE_TELEPORT),
    SPELL_TELEKINETIC_GRAB(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.TELEKINETIC_GRAB),
    SPELL_FIRE_BOLT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.FIRE_BOLT),
    SPELL_FALADOR_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.FALADOR_TELEPORT),
    SPELL_CRUMBLE_UNDEAD(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.CRUMBLE_UNDEAD),
    SPELL_TELEPORT_TO_HOUSE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.TELEPORT_TO_HOUSE),
    SPELL_WIND_BLAST(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.WIND_BLAST),
    SPELL_SUPERHEAT_ITEM(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.SUPERHEAT_ITEM),
    SPELL_CAMELOT_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.CAMELOT_TELEPORT),
    SPELL_WATER_BLAST(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.WATER_BLAST),
    SPELL_LVL_3_ENCHANT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.LVL_3_ENCHANT),
    SPELL_IBAN_BLAST(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.IBAN_BLAST),
    SPELL_SNARE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.SNARE),
    SPELL_MAGIC_DART(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.MAGIC_DART),
    SPELL_ARDOUGNE_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.ARDOUGNE_TELEPORT),
    SPELL_EARTH_BLAST(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.EARTH_BLAST),
    SPELL_CIVITAS_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.CIVITAS_TELEPORT),
    SPELL_HIGH_LEVEL_ALCHEMY(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.HIGH_LEVEL_ALCHEMY),
    SPELL_CHARGE_WATER_ORB(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.CHARGE_WATER_ORB),
    SPELL_LVL_4_ENCHANT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.LVL_4_ENCHANT),
    SPELL_WATCHTOWER_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.WATCHTOWER_TELEPORT),
    SPELL_FIRE_BLAST(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.FIRE_BLAST),
    SPELL_CHARGE_EARTH_ORB(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.CHARGE_EARTH_ORB),
    SPELL_BONES_TO_PEACHES(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.BONES_TO_PEACHES),
    SPELL_SARADOMIN_STRIKE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.SARADOMIN_STRIKE),
    SPELL_CLAWS_OF_GUTHIX(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.CLAWS_OF_GUTHIX),
    SPELL_FLAMES_OF_ZAMORAK(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.FLAMES_OF_ZAMORAK),
    SPELL_TROLLHEIM_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.TROLLHEIM_TELEPORT),
    SPELL_WIND_WAVE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.WIND_WAVE),
    SPELL_CHARGE_FIRE_ORB(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.CHARGE_FIRE_ORB),
    SPELL_TELEPORT_TO_APE_ATOLL(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.TELEPORT_TO_APE_ATOLL),
    SPELL_WATER_WAVE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.WATER_WAVE),
    SPELL_CHARGE_AIR_ORB(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.CHARGE_AIR_ORB),
    SPELL_VULNERABILITY(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.VULNERABILITY),
    SPELL_LVL_5_ENCHANT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.LVL_5_ENCHANT),
    SPELL_TELEPORT_TO_KOUREND(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.TELEPORT_TO_KOUREND),
    SPELL_EARTH_WAVE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.EARTH_WAVE),
    SPELL_ENFEEBLE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.ENFEEBLE),
    SPELL_FIRE_WAVE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.FIRE_WAVE),
    SPELL_ENTANGLE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.ENTANGLE),
    SPELL_TELEOTHER_LUMBRIDGE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.TELEOTHER_LUMBRIDGE),
    SPELL_STUN(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.STUN),
    SPELL_CHARGE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.CHARGE),
    SPELL_WIND_SURGE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.WIND_SURGE),
    SPELL_TELEOTHER_FALADOR(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.TELEOTHER_FALADOR),
    SPELL_WATER_SURGE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.WATER_SURGE),
    SPELL_TELE_BLOCK(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.TELE_BLOCK),
    SPELL_LVL_6_ENCHANT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.LVL_6_ENCHANT),
    SPELL_TELEOTHER_CAMELOT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.TELEOTHER_CAMELOT),
    SPELL_EARTH_SURGE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.EARTH_SURGE),
    SPELL_LVL_7_ENCHANT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.LVL_7_ENCHANT),
    SPELL_FIRE_SURGE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.FIRE_SURGE),
    SPELL_BOUNTY_TARGET_TELEPORT2(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.BOUNTY_TARGET_TELEPORT),
    SPELL_TELEPORT_BOAT_TO_ME(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.TELEPORT_BOAT_TO_ME),
    SPELL_TELEPORT_ME_TO_BOAT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.TELEPORT_ME_TO_BOAT),
    SPELL_MONSTER_INSPECT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.MONSTER_INSPECT),
    /* END OF STANDARD SPELL BOOK WIDGETS*/

    /* ANCIENT SPELL BOOK WIDGETS*/
    SPELL_ICE_RUSH(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.ICE_RUSH),
    SPELL_ICE_BLITZ(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.ICE_BLITZ),
    SPELL_ICE_BURST(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.ICE_BURST),
    SPELL_ICE_BARRAGE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.ICE_BARRAGE),
    SPELL_BLOOD_RUSH(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.BLOOD_RUSH),
    SPELL_BLOOD_BLITZ(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.BLOOD_BLITZ),
    SPELL_BLOOD_BURST(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.BLOOD_BURST),
    SPELL_BLOOD_BARRAGE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.BLOOD_BARRAGE),
    SPELL_SMOKE_RUSH(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.SMOKE_RUSH),
    SPELL_SMOKE_BLITZ(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.SMOKE_BLITZ),
    SPELL_SMOKE_BURST(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.SMOKE_BURST),
    SPELL_SMOKE_BARRAGE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.SMOKE_BARRAGE),
    SPELL_SHADOW_RUSH(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.SHADOW_RUSH),
    SPELL_SHADOW_BLITZ(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.SHADOW_BLITZ),
    SPELL_SHADOW_BURST(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.SHADOW_BURST),
    SPELL_SHADOW_BARRAGE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.SHADOW_BARRAGE),
    SPELL_EDGEVILLE_HOME_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.EDGEVILLE_HOME_TELEPORT),
    SPELL_PADDEWWA_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.PADDEWWA_TELEPORT),
    SPELL_SENNTISTEN_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.SENNTISTEN_TELEPORT),
    SPELL_KHARYRLL_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.KHARYRLL_TELEPORT),
    SPELL_LASSAR_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.LASSAR_TELEPORT),
    SPELL_DAREEYAK_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.DAREEYAK_TELEPORT),
    SPELL_CARRALLANGER_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.CARRALLANGER_TELEPORT),
    SPELL_ANNAKARL_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.ANNAKARL_TELEPORT),
    SPELL_GHORROCK_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.GHORROCK_TELEPORT),
    SPELL_BOUNTY_TARGET_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.BOUNTY_TARGET_TELEPORT),
    /* END OF ANCIENT SPELL BOOK WIDGETS*/

    /* LUNAR SPELL BOOK WIDGETS*/
    SPELL_LUNAR_HOME_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.LUNAR_HOME_TELEPORT),
    SPELL_VENGEANCE_OTHER(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.VENGEANCE_OTHER),
    SPELL_VENGEANCE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.VENGEANCE),
    SPELL_BOUNTY_TARGET_TELEPORT3(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.BOUNTY_TARGET_TELEPORT),
    SPELL_BAKE_PIE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.BAKE_PIE),
    SPELL_CURE_PLANT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.CURE_PLANT),
    SPELL_MONSTER_EXAMINE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.MONSTER_EXAMINE),
    SPELL_NPC_CONTACT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.NPC_CONTACT),
    SPELL_CURE_OTHER(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.CURE_OTHER),
    SPELL_HUMIDIFY(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.HUMIDIFY),
    SPELL_MOONCLAN_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.MOONCLAN_TELEPORT),
    SPELL_TELE_GROUP_MOONCLAN(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.TELE_GROUP_MOONCLAN),
    SPELL_CURE_ME(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.CURE_ME),
    SPELL_HUNTER_KIT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.HUNTER_KIT),
    SPELL_WATERBIRTH_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.WATERBIRTH_TELEPORT),
    SPELL_TELE_GROUP_WATERBIRTH(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.TELE_GROUP_WATERBIRTH),
    SPELL_CURE_GROUP(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.CURE_GROUP),
    SPELL_STAT_SPY(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.STAT_SPY),
    SPELL_BARBARIAN_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.BARBARIAN_TELEPORT),
    SPELL_TELE_GROUP_BARBARIAN(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.TELE_GROUP_BARBARIAN),
    SPELL_SUPERGLASS_MAKE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.SUPERGLASS_MAKE),
    SPELL_TAN_LEATHER(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.TAN_LEATHER),
    SPELL_KHAZARD_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.KHAZARD_TELEPORT),
    SPELL_TELE_GROUP_KHAZARD(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.TELE_GROUP_KHAZARD),
    SPELL_DREAM(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.DREAM),
    SPELL_STRING_JEWELLERY(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.STRING_JEWELLERY),
    SPELL_STAT_RESTORE_POT_SHARE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.STAT_RESTORE_POT_SHARE),
    SPELL_MAGIC_IMBUE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.MAGIC_IMBUE),
    SPELL_FERTILE_SOIL(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.FERTILE_SOIL),
    SPELL_BOOST_POTION_SHARE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.BOOST_POTION_SHARE),
    SPELL_FISHING_GUILD_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.FISHING_GUILD_TELEPORT),
    SPELL_TELE_GROUP_FISHING_GUILD(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.TELE_GROUP_FISHING_GUILD),
    SPELL_PLANK_MAKE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.PLANK_MAKE),
    SPELL_CATHERBY_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.CATHERBY_TELEPORT),
    SPELL_TELE_GROUP_CATHERBY(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.TELE_GROUP_CATHERBY),
    SPELL_RECHARGE_DRAGONSTONE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.RECHARGE_DRAGONSTONE),
    SPELL_ICE_PLATEAU_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.ICE_PLATEAU_TELEPORT),
    SPELL_TELE_GROUP_ICE_PLATEAU(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.TELE_GROUP_ICE_PLATEAU),
    SPELL_ENERGY_TRANSFER(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.ENERGY_TRANSFER),
    SPELL_HEAL_OTHER(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.HEAL_OTHER),
    SPELL_HEAL_GROUP(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.HEAL_GROUP),
    SPELL_SPELLBOOK_SWAP(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.SPELLBOOK_SWAP),
    SPELL_GEOMANCY(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.GEOMANCY),
    SPELL_SPIN_FLAX(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.SPIN_FLAX),
    SPELL_OURANIA_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.OURANIA_TELEPORT),
    /* END OF LUNAR SPELL BOOK WIDGETS*/
    SPELL_TOOLTIP(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.TOOLTIP),
    /* ARCEUUS SPELL BOOK WIDGETS*/
    SPELL_ARCEUUS_HOME_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.ARCEUUS_HOME_TELEPORT),
    SPELL_BASIC_REANIMATION(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.BASIC_REANIMATION),
    SPELL_ARCEUUS_LIBRARY_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.ARCEUUS_LIBRARY_TELEPORT),
    SPELL_ADEPT_REANIMATION(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.ADEPT_REANIMATION),
    SPELL_EXPERT_REANIMATION(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.EXPERT_REANIMATION),
    SPELL_MASTER_REANIMATION(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.MASTER_REANIMATION),
    SPELL_DRAYNOR_MANOR_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.DRAYNOR_MANOR_TELEPORT),
    SPELL_MIND_ALTAR_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.MIND_ALTAR_TELEPORT),
    SPELL_RESPAWN_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.RESPAWN_TELEPORT),
    SPELL_SALVE_GRAVEYARD_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.SALVE_GRAVEYARD_TELEPORT),
    SPELL_FENKENSTRAINS_CASTLE_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.FENKENSTRAINS_CASTLE_TELEPORT),
    SPELL_WEST_ARDOUGNE_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.WEST_ARDOUGNE_TELEPORT),
    SPELL_HARMONY_ISLAND_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.HARMONY_ISLAND_TELEPORT),
    SPELL_CEMETERY_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.CEMETERY_TELEPORT),
    SPELL_RESURRECT_CROPS(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.RESURRECT_CROPS),
    SPELL_BARROWS_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.BARROWS_TELEPORT),
    SPELL_APE_ATOLL_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.APE_ATOLL_TELEPORT),
    SPELL_BATTLEFRONT_TELEPORT(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.BATTLEFRONT_TELEPORT),
    SPELL_INFERIOR_DEMONBANE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.INFERIOR_DEMONBANE),
    SPELL_SUPERIOR_DEMONBANE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.SUPERIOR_DEMONBANE),
    SPELL_DARK_DEMONBANE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.DARK_DEMONBANE),
    SPELL_MARK_OF_DARKNESS(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.MARK_OF_DARKNESS),
    SPELL_GHOSTLY_GRASP(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.GHOSTLY_GRASP),
    SPELL_SKELETAL_GRASP(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.SKELETAL_GRASP),
    SPELL_UNDEAD_GRASP(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.UNDEAD_GRASP),
    SPELL_WARD_OF_ARCEUUS(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.WARD_OF_ARCEUUS),
    SPELL_LESSER_CORRUPTION(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.LESSER_CORRUPTION),
    SPELL_GREATER_CORRUPTION(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.GREATER_CORRUPTION),
    SPELL_DEMONIC_OFFERING(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.DEMONIC_OFFERING),
    SPELL_SINISTER_OFFERING(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.SINISTER_OFFERING),
    SPELL_DEGRIME(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.DEGRIME),
    SPELL_SHADOW_VEIL(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.SHADOW_VEIL),
    SPELL_VILE_VIGOUR(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.VILE_VIGOUR),
    SPELL_DARK_LURE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.DARK_LURE),
    SPELL_DEATH_CHARGE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.DEATH_CHARGE),
    SPELL_RESURRECT_LESSER_GHOST(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.RESURRECT_LESSER_GHOST),
    SPELL_RESURRECT_LESSER_SKELETON(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.RESURRECT_LESSER_SKELETON),
    SPELL_RESURRECT_LESSER_ZOMBIE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.RESURRECT_LESSER_ZOMBIE),
    SPELL_RESURRECT_SUPERIOR_GHOST(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.RESURRECT_SUPERIOR_GHOST),
    SPELL_RESURRECT_SUPERIOR_SKELETON(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.RESURRECT_SUPERIOR_SKELETON),
    SPELL_RESURRECT_SUPERIOR_ZOMBIE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.RESURRECT_SUPERIOR_ZOMBIE),
    SPELL_RESURRECT_GREATER_GHOST(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.RESURRECT_GREATER_GHOST),
    SPELL_RESURRECT_GREATER_SKELETON(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.RESURRECT_GREATER_SKELETON),
    SPELL_RESURRECT_GREATER_ZOMBIE(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.RESURRECT_GREATER_ZOMBIE),
    SPELL_BOUNTY_TARGET_TELEPORT4(WidgetIDExtended.SPELLBOOK_GROUP_ID, WidgetIDExtended.SpellBook.BOUNTY_TARGET_TELEPORT),

    /* END OF ARCEUUS SPELL BOOK WIDGETS*/

    MULTICOMBAT_RESIZEABLE(WidgetIDExtended.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, WidgetIDExtended.ResizableViewport.MULTICOMBAT_INDICATOR),

    MUSICTAB_INTERFACE(WidgetIDExtended.MUSICTAB_GROUP_ID, 1),
    MUSICTAB_SONG_BOX(WidgetIDExtended.MUSICTAB_GROUP_ID, 2),
    MUSICTAB_ALL_SONGS(WidgetIDExtended.MUSICTAB_GROUP_ID, 3),
    MUSICTAB_SCROLLBAR(WidgetIDExtended.MUSICTAB_GROUP_ID, 4),
    MUSICTAB_PLAYING(WidgetIDExtended.MUSICTAB_GROUP_ID, 5),
    MUSICTAB_CURRENT_SONG_NAME(WidgetIDExtended.MUSICTAB_GROUP_ID, 6),
    MUSICTAB_AUTO_BUTTON_LISTENER(WidgetIDExtended.MUSICTAB_GROUP_ID, 7),
    MUSICTAB_AUTO_BUTTON(WidgetIDExtended.MUSICTAB_GROUP_ID, 8),
    MUSICTAB_MANUAL_BUTTON_LISTENER(WidgetIDExtended.MUSICTAB_GROUP_ID, 9),
    MUSICTAB_MANUAL_BUTTON(WidgetIDExtended.MUSICTAB_GROUP_ID, 10),
    MUSICTAB_LOOP_BUTTON_LISTENER(WidgetIDExtended.MUSICTAB_GROUP_ID, 11),
    MUSICTAB_LOOP_BUTTON(WidgetIDExtended.MUSICTAB_GROUP_ID, 12),
    MUSICTAB_UNLOCKED_SONGS(WidgetIDExtended.MUSICTAB_GROUP_ID, 13),

    QUESTTAB_QUEST_TAB(WidgetIDExtended.QUESTTAB_GROUP_ID, WidgetIDExtended.QuestTab.QUEST_TAB),

    EQUIPMENT_MELEE_STRENGTH(WidgetIDExtended.EQUIPMENT_PAGE_GROUP_ID, WidgetIDExtended.EquipmentWidgetIdentifiers.MELEE_STRENGTH),
    EQUIPMENT_RANGED_STRENGTH(WidgetIDExtended.EQUIPMENT_PAGE_GROUP_ID, WidgetIDExtended.EquipmentWidgetIdentifiers.RANGED_STRENGTH),
    EQUIPMENT_MAGIC_DAMAGE(WidgetIDExtended.EQUIPMENT_PAGE_GROUP_ID, WidgetIDExtended.EquipmentWidgetIdentifiers.MAGIC_DAMAGE),
    EQUIP_YOUR_CHARACTER(WidgetIDExtended.EQUIPMENT_PAGE_GROUP_ID, WidgetIDExtended.EquipmentWidgetIdentifiers.EQUIP_YOUR_CHARACTER),
    TRADING_WITH(WidgetIDExtended.PLAYER_TRADE_SCREEN_GROUP_ID, WidgetIDExtended.TradeScreen.FIRST_TRADING_WITH),
    SECOND_TRADING_WITH(WidgetIDExtended.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetIDExtended.TradeScreen.SECOND_TRADING_WITH),
    SECOND_TRADING_WITH_ACCEPT_BUTTON(WidgetIDExtended.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetIDExtended.TradeScreen.SECOND_ACCEPT_FUNC),
    SECOND_TRADING_WITH_ACCEPT_TEXT(WidgetIDExtended.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetIDExtended.TradeScreen.SECOND_ACCEPT_TEXT),
    SECOND_TRADING_WITH_DECLINE_BUTTON(WidgetIDExtended.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetIDExtended.TradeScreen.SECOND_DECLINE_FUNC),
    SECOND_TRADING_WITH_DECLINE_TEXT(WidgetIDExtended.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetIDExtended.TradeScreen.SECOND_DECLINE_TEXT),
    SECOND_TRADING_WITH_MY_OFFER(WidgetIDExtended.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetIDExtended.TradeScreen.SECOND_MY_OFFER),
    SECOND_TRADING_WITH_THEIR_OFFER(WidgetIDExtended.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetIDExtended.TradeScreen.SECOND_THEIR_OFFER),
    SECOND_TRADING_WITH_MY_ITEMS(WidgetIDExtended.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetIDExtended.TradeScreen.SECOND_MY_ITEMS),
    SECOND_TRADING_WITH_THEIR_ITEMS(WidgetIDExtended.PLAYER_TRADE_CONFIRM_GROUP_ID, WidgetIDExtended.TradeScreen.SECOND_THEIR_ITEMS),
    ;

    private final int groupId;
    private final int childId;

    WidgetInfoExtended(int groupId, int childId) {
        this.groupId = groupId;
        this.childId = childId;
    }

    /**
     * Gets the ID of the group-child pairing.
     *
     * @return the ID
     */
    public int getId() {
        return groupId << 16 | childId;
    }

    /**
     * Gets the group ID of the pair.
     *
     * @return the group ID
     */
    public int getGroupId() {
        return groupId;
    }

    /**
     * Gets the ID of the child in the group.
     *
     * @return the child ID
     */
    public int getChildId() {
        return childId;
    }

    /**
     * Gets the packed widget ID.
     *
     * @return the packed ID
     */
    public int getPackedId() {
        return groupId << 16 | childId;
    }

    /**
     * Utility method that converts an ID returned by {@link #getId()} back
     * to its group ID.
     *
     * @param id passed group-child ID
     * @return the group ID
     */
    public static int TO_GROUP(int id) {
        return id >>> 16;
    }

    /**
     * Utility method that converts an ID returned by {@link #getId()} back
     * to its child ID.
     *
     * @param id passed group-child ID
     * @return the child ID
     */
    public static int TO_CHILD(int id) {
        return id & 0xFFFF;
    }

    /**
     * Packs the group and child IDs into a single integer.
     *
     * @param groupId the group ID
     * @param childId the child ID
     * @return the packed ID
     */
    public static int PACK(int groupId, int childId) {
        return groupId << 16 | childId;
    }

    public static WidgetInfoExtended valueOf(int packedId) {
        return Arrays.stream(values()).filter(w -> w.getId() == packedId).findAny().orElse(null);
    }
}
